export interface Kit {
  id: number;
  name: string;
  club: string;
  season: string;
  price: number;
  number: string;
  league: string;
  gradient: string;
  badge: string | null;
  image: string;
  color: string;
  stock?: number;
  sizeStock?: Record<string, number>;
  backImage?: string;
  description?: string;
  productType?: "jersey" | "embroidery" | "retro-player" | "jacket" | "f1" | "kids";
  customizationAvailable?: boolean;
  isDraft?: boolean;
  isPrivate?: boolean;
  isArchived?: boolean;
  isRemoved?: boolean;
}

const TEXT_ONLY_SIZE_STOCK = { S: 10, M: 10, L: 10, XL: 10 }

const textOnlyJackets: Kit[] = [
  ["AC Milan", "Black and Red Retro Track Jacket", "Serie A", "Black/red", "ac-milan-black-red-retro-track-jacket"],
  ["Italy", "Black and Blue Retro Track Jacket", "International", "Black/blue", "italy-black-blue-retro-track-jacket"],
  ["Manchester United", "Blue Retro Track Jacket", "Premier League", "Blue/white", "manchester-united-blue-retro-track-jacket"],
  ["Chelsea", "Black Nike Retro Track Jacket", "Premier League", "Black/blue", "chelsea-black-retro-track-jacket"],
  ["Manchester United", "Black Pattern Retro Track Jacket", "Premier League", "Black/red", "manchester-united-pattern-retro-track-jacket"],
  ["Arsenal", "Red Retro Track Jacket", "Premier League", "Red/yellow", "arsenal-red-retro-track-jacket"],
  ["Borussia Dortmund", "Black Retro Track Jacket", "Bundesliga", "Black/yellow", "borussia-dortmund-retro-track-jacket"],
  ["France", "Blue 1998 Style Retro Track Jacket", "International", "Blue/red", "france-blue-retro-track-jacket"],
  ["Paris Saint-Germain", "Burgundy Jordan Retro Track Jacket", "Ligue 1", "Burgundy/white", "psg-burgundy-jordan-retro-track-jacket"],
  ["Manchester City", "Navy Puma Retro Track Jacket", "Premier League", "Navy/sky blue", "manchester-city-navy-retro-track-jacket"],
  ["Real Madrid", "Navy Adidas Retro Track Jacket", "La Liga", "Navy/orange", "real-madrid-navy-orange-retro-track-jacket"],
  ["Italy", "Navy Puma Retro Track Jacket", "International", "Navy/yellow", "italy-navy-yellow-retro-track-jacket"],
  ["Real Madrid", "Navy and Sky Blue Track Jacket", "La Liga", "Navy/sky blue", "real-madrid-navy-sky-retro-track-jacket"],
  ["Bayern Munich", "Red and Blue Retro Track Jacket", "Bundesliga", "Red/blue", "bayern-red-blue-retro-track-jacket"],
  ["Real Madrid", "Navy and White Retro Track Jacket", "La Liga", "Navy/white", "real-madrid-navy-white-retro-track-jacket"],
  ["Germany", "White 1990 Style Retro Track Jacket", "International", "White/black/red/yellow", "germany-white-retro-track-jacket"],
  ["Paris Saint-Germain", "Blue and Red Nike Retro Track Jacket", "Ligue 1", "Blue/red", "psg-blue-red-retro-track-jacket"],
].map(([club, name, league, color, assetSlug], index) => ({
  id: 200 + index,
  name,
  club,
  season: "Retro football track jacket",
  price: 1899,
  number: "Jacket",
  league,
  gradient: "from-[#111111] via-[#3f3f46] to-[#f8fafc]",
  badge: "Jacket",
  image: `/kits/idk-clean/${assetSlug}-front.jpg`,
  backImage: `/kits/idk-clean/${assetSlug}-back.jpg`,
  color,
  stock: 40,
  sizeStock: { ...TEXT_ONLY_SIZE_STOCK },
  productType: "jacket",
  customizationAvailable: false,
  description: `${club} ${name.toLowerCase()}. Premium retro football outerwear with a full-zip track-jacket finish.`,
}))

const textOnlyRetroPlayerKits: Kit[] = [
  ["France", "France Away Retro Jersey", "2006/07", "International", "White/red/blue", "france-away-2006-07-retro"],
  ["Real Madrid", "Real Madrid Home Retro Jersey", "1999/2000", "La Liga", "White/black", "real-madrid-home-1999-2000-retro"],
  ["Manchester United", "Manchester United Away Retro Jersey", "1997/98", "Premier League", "White/black/red", "manchester-united-away-1997-98-retro"],
  ["Germany", "Germany Home Retro Jersey", "2005/06", "International", "White/black/red/yellow", "germany-home-2005-06-retro"],
  ["Real Madrid", "Real Madrid Away Retro Jersey", "2011/12", "La Liga", "Black/gold", "real-madrid-away-2011-12-retro"],
  ["Real Madrid", "Real Madrid Home Retro Jersey", "1996/97", "La Liga", "White/blue", "real-madrid-home-1996-97-retro"],
  ["Real Madrid", "Real Madrid Home Retro Jersey", "2011/12", "La Liga", "White/gold", "real-madrid-home-2011-12-retro"],
  ["AC Milan", "AC Milan Third Retro Jersey", "2005/06", "Serie A", "Black/red", "ac-milan-third-2005-06-retro"],
  ["Real Madrid", "Real Madrid Home Retro Jersey", "2017/18", "La Liga", "White/teal", "real-madrid-home-2017-18-retro"],
  ["Manchester United", "Manchester United Away Retro Jersey", "2008/09", "Premier League", "Black/red", "manchester-united-away-2008-09-retro"],
  ["Real Madrid", "Real Madrid Away Retro Jersey", "2010/11", "La Liga", "Navy/neon yellow", "real-madrid-away-2010-11-retro"],
  ["Real Madrid", "Real Madrid Home Retro Jersey", "2014/15", "La Liga", "White/black", "real-madrid-home-2014-15-retro"],
  ["Germany", "Germany Home Retro Jersey", "1990", "International", "White/black", "germany-home-1990-retro"],
  ["Barcelona", "Barcelona Away Retro Jersey", "2003/04", "La Liga", "White/red/blue", "barcelona-away-2003-04-retro"],
  ["Barcelona", "Barcelona Away Retro Jersey", "2010/11", "La Liga", "Mint/navy", "barcelona-away-2010-11-retro"],
  ["Brazil", "Brazil Home Retro Jersey", "1998/99", "International", "Yellow/green", "brazil-home-1998-99-retro"],
].map(([club, name, season, league, color, assetSlug], index) => ({
  id: 217 + index,
  name,
  club,
  season: `${season} - Player Version`,
  price: 1299,
  number: "No name",
  league,
  gradient: "from-[#111111] via-[#52525b] to-[#f8fafc]",
  badge: "Retro Player",
  image: `/kits/idk-clean/${assetSlug}-front.jpg`,
  backImage: `/kits/idk-clean/${assetSlug}-back.jpg`,
  color,
  stock: 40,
  sizeStock: { ...TEXT_ONLY_SIZE_STOCK },
  productType: "retro-player",
  customizationAvailable: false,
  description: `${club} ${season} retro jersey in Player Version quality. Sold without sleeve patches and without a printed player name or number.`,
}))

const NEW_CLUB_DROP_NAMES: Record<number, string> = {
  300: "Manchester United Home 2026-27",
  301: "Juventus Home 2026-27",
  302: "Real Madrid Originals Jersey",
  303: "Tottenham Away 2025-26",
  304: "FC Barcelona Third 2025-26",
  305: "Manchester United Third 2025-26",
  306: "FC Barcelona Pastel Concept 2025-26",
  307: "Paris Saint-Germain x Jordan Wings 2024-25",
  308: "Arsenal Third 2025-26",
  309: "AC Milan Home 2025-26",
  310: "Liverpool Home 2025-26",
  311: "Bayern Munich Third 2025-26",
  312: "FC Barcelona Vintage Concept 2025-26",
  313: "Juventus Pink Concept 2025-26",
  314: "Chelsea Third 2025-26",
  316: "FC Barcelona x Travis Scott 2024-25",
  317: "FC Barcelona x Kobe Away 2026-27",
  318: "Manchester United Home 1982-84 Retro",
  319: "Liverpool Third 2025-26",
  320: "Bayern Munich Home 2025-26",
  321: "Chelsea Home 2025-26",
  322: "Paris Saint-Germain Home 2025-26",
  323: "Inter Miami Riptide Third 2025",
  324: "Manchester City Home 2025-26",
  325: "Arsenal Away 2025-26",
  326: "Real Madrid Home 2026-27",
}

const imported2026DropKits = [
  { id: 327, name: "Real Madrid x Louis Vuitton Concept", club: "Real Madrid", season: "Concept 2026-27", league: "La Liga", badge: "Concept Kit", slug: "real-madrid-louis-vuitton-concept", description: "Real Madrid concept jersey in tonal black with a fold-over collar, white club detailing and a subtle monogram-inspired body pattern." },
  { id: 328, name: "Chelsea Oracle Concept", club: "Chelsea", season: "Concept 2026-27", league: "Premier League", badge: "Concept Kit", slug: "chelsea-oracle-concept", description: "Chelsea concept jersey in understated black with fine vertical texture, yellow Nike and crest details and an Oracle chest mark." },
  { id: 329, name: "Manchester City Black Gold Concept", club: "Manchester City", season: "Concept 2026-27", league: "Premier League", badge: "Concept Kit", slug: "manchester-city-black-gold-concept", description: "Manchester City concept jersey pairing a black geometric base with metallic-gold club, Puma and Etihad details." },
  { id: 330, name: "AC Milan Home 2026-27", club: "AC Milan", season: "Home 2026-27", league: "Serie A", badge: "New 26/27", slug: "ac-milan-home-2026-27", description: "AC Milan home jersey with broad red-and-black vertical stripes, white Puma branding and the Emirates Fly Better sponsor." },
  { id: 331, name: "Aston Villa Home 2026-27", club: "Aston Villa", season: "Home 2026-27", league: "Premier League", badge: "New 26/27", slug: "aston-villa-home-2026-27", description: "Aston Villa home jersey in deep claret with a sky-blue polo collar, matching shoulder stripes and lightweight performance-knit panels." },
  { id: 332, name: "Barcelona Cross Concept", club: "FC Barcelona", season: "Concept 2026-27", league: "La Liga", badge: "Concept Kit", slug: "barcelona-cross-concept", description: "Barcelona concept jersey using a cream base and bold red cross, finished with navy trim and the Spotify mark." },
  { id: 333, name: "Bayern Munich Home 2026-27", club: "Bayern Munich", season: "Home 2026-27", league: "Bundesliga", badge: "New 26/27", slug: "bayern-munich-home-2026-27", description: "Bayern Munich home jersey in vivid red with tonal pinstripes, white shoulder stripes and classic Telekom branding." },
  { id: 334, name: "Borussia Dortmund Vodafone Concept", club: "Borussia Dortmund", season: "Concept 2026-27", league: "Bundesliga", badge: "Concept Kit", slug: "borussia-dortmund-vodafone-concept", description: "Borussia Dortmund concept jersey in signature yellow with black side panels, striped cuffs and a bold Vodafone chest mark." },
  { id: 335, name: "Paris Saint-Germain Home 2026-27", club: "Paris Saint-Germain", season: "Home 2026-27", league: "Ligue 1", badge: "New 26/27", slug: "psg-home-2026-27", description: "Paris Saint-Germain home jersey restoring a strong red centre stripe bordered in white across a royal-blue base." },
  { id: 336, name: "AC Milan Third 2026-27", club: "AC Milan", season: "Third 2026-27", league: "Serie A", badge: "New 26/27", slug: "ac-milan-black-third-2026-27", description: "AC Milan third jersey in black with sharp red-orange crest, sponsor and trim details for a clean high-contrast finish." },
  { id: 337, name: "Paris Saint-Germain Pre-Match 2026-27", club: "Paris Saint-Germain", season: "Pre-Match 2026-27", league: "Ligue 1", badge: "New 26/27", slug: "psg-white-away-2026-27", description: "Paris Saint-Germain 2026-27 pre-match jersey in white with a broad red horizontal chest band, slim navy borders and coordinated collar and sleeve trim." },
  { id: 338, name: "Manchester United White Concept", club: "Manchester United", season: "Concept 2026-27", league: "Premier League", badge: "Concept Kit", slug: "manchester-united-white-concept", description: "Manchester United concept jersey in white with burgundy and green accents, tonal technical texture and a stripped-back crest treatment." },
  { id: 339, name: "Real Madrid Third 2026-27", club: "Real Madrid", season: "Third 2026-27", league: "La Liga", badge: "New 26/27", slug: "real-madrid-magenta-away-2026-27", description: "Real Madrid third jersey in rich magenta with cream adidas stripes, a V-neck collar and tonal performance-knit patterning." },
  { id: 340, name: "Manchester United Away 2026-27", club: "Manchester United", season: "Away 2026-27", league: "Premier League", badge: "New 26/27", slug: "manchester-united-blue-away-2026-27", description: "Manchester United away jersey in royal blue with red-and-white trim, Trefoil branding and the Snapdragon sponsor." },
  { id: 341, name: "Manchester City Third 2026-27", club: "Manchester City", season: "Third 2026-27", league: "Premier League", badge: "New 26/27", slug: "manchester-city-white-away-2026-27", description: "Manchester City third jersey in white with a central stripe fading from sky blue to navy and matching side-panel accents." },
  { id: 342, name: "Arsenal Home 2026-27", club: "Arsenal", season: "Home 2026-27", league: "Premier League", badge: "New 26/27", slug: "arsenal-home-2026-27", description: "Arsenal home jersey in red with pale sleeves, burgundy shoulder stripes and textured collar and cuff details." },
  { id: 343, name: "Barcelona Home 2026-27", club: "FC Barcelona", season: "Home 2026-27", league: "La Liga", badge: "New 26/27", slug: "barcelona-home-2026-27-new", description: "Barcelona home jersey with alternating garnet, royal-blue and deep-navy stripes, yellow club marks and Spotify sponsor." },
  { id: 344, name: "Newcastle United Home 2026-27", club: "Newcastle United", season: "Home 2026-27", league: "Premier League", badge: "New 26/27", slug: "newcastle-home-2026-27", description: "Newcastle United home jersey with narrow black-and-white striping, blue trim and the Sela chest sponsor." },
  { id: 345, name: "AC Milan Away 2026-27", club: "AC Milan", season: "Away 2026-27", league: "Serie A", badge: "New 26/27", slug: "ac-milan-white-away-2026-27", description: "AC Milan away jersey in white with a tonal wave texture, gold Puma mark and an ornate heritage-style crest." },
  { id: 346, name: "Bayern Munich Away 2026-27", club: "Bayern Munich", season: "Away 2026-27", league: "Bundesliga", badge: "New 26/27", slug: "bayern-munich-white-away-2026-27", description: "Bayern Munich away jersey in white with a navy fold-over collar, red trim, Trefoil branding and Telekom sponsor." },
  { id: 347, name: "Tottenham Hotspur Home 2026-27", club: "Tottenham Hotspur", season: "Home 2026-27", league: "Premier League", badge: "New 26/27", slug: "tottenham-home-2026-27", description: "Tottenham Hotspur home jersey in crisp white with subtle diagonal texture, navy details and the red AIA sponsor." },
  { id: 348, name: "Arsenal Third 2026-27", club: "Arsenal", season: "Third 2026-27", league: "Premier League", badge: "New 26/27", slug: "arsenal-gold-away-2026-27", description: "Arsenal third jersey in pale gold with burgundy and navy trim, tonal diagonal texture and the cannon crest." },
  { id: 349, name: "Manchester City Home 2026-27", club: "Manchester City", season: "Home 2026-27", league: "Premier League", badge: "New 26/27", slug: "manchester-city-home-2026-27-new", description: "Manchester City home jersey in clean sky blue with white collar and cuffs, tonal Puma marks and Etihad sponsor." },
  { id: 350, name: "Celtic Home 2026-27", club: "Celtic", season: "Home 2026-27", league: "Scottish Premiership", badge: "New 26/27", slug: "celtic-home-2026-27", description: "Celtic home jersey with green-and-white hoops, gold club and sponsor detailing and white raglan shoulders." },
  { id: 351, name: "Arsenal Green Special Edition", club: "Arsenal", season: "Special Edition", league: "Premier League", badge: "Special Edition", slug: "arsenal-green-third-2026-27", description: "Arsenal special-edition jersey in deep green with an all-over botanical pattern, white sleeves and a heritage polo collar." },
  { id: 352, name: "Real Madrid Tonal White Concept", club: "Real Madrid", season: "Concept 2026-27", league: "La Liga", badge: "Concept Kit", slug: "real-madrid-tonal-white-concept", description: "Real Madrid concept jersey in layered tonal white with a polo collar, subtle Trefoil, crest and sponsor treatment." },
  { id: 353, name: "Arsenal Navy Away 2026-27", club: "Arsenal", season: "Away 2026-27", league: "Premier League", badge: "New 26/27", slug: "arsenal-navy-away-2026-27", description: "Arsenal away jersey in patterned navy with bright yellow marks and red-and-yellow collar and cuff trim." },
  { id: 354, name: "Liverpool Away 2026-27", club: "Liverpool", season: "Away 2026-27", league: "Premier League", badge: "New 26/27", slug: "liverpool-white-away-2026-27", description: "Liverpool away jersey in white with tonal graphics, burgundy Trefoil, crest and sponsor, and striped V-neck trim." },
  { id: 355, name: "Real Madrid Home Long Sleeve 2026-27", club: "Real Madrid", season: "Home 2026-27 - long sleeve", league: "La Liga", badge: "New 26/27", slug: "real-madrid-home-long-sleeve-2026-27", description: "Real Madrid long-sleeve home jersey in white with burgundy adidas sleeve stripes, dark cuffs and a clean plain back." },
  { id: 356, name: "Real Madrid Third Long Sleeve 2026-27", club: "Real Madrid", season: "Third 2026-27 - long sleeve", league: "La Liga", badge: "New 26/27", slug: "real-madrid-magenta-long-sleeve-2026-27", description: "Real Madrid long-sleeve third jersey in magenta with cream shoulder and sleeve stripes and tonal body pattern." },
  { id: 357, name: "Liverpool Home Long Sleeve 2026-27", club: "Liverpool", season: "Home 2026-27 - long sleeve", league: "Premier League", badge: "New 26/27", slug: "liverpool-red-long-sleeve-2026-27", description: "Liverpool long-sleeve home jersey in red with an energetic white geometric print and white adidas sleeve stripes." },
  { id: 358, name: "Arsenal Away Long Sleeve 2026-27", club: "Arsenal", season: "Away 2026-27 - long sleeve", league: "Premier League", badge: "New 26/27", slug: "arsenal-navy-long-sleeve-2026-27", description: "Arsenal long-sleeve away jersey in patterned navy with yellow branding and red-and-yellow collar and cuff trim." },
  { id: 359, name: "Liverpool Home 2026-27", club: "Liverpool", season: "Home 2026-27 - short sleeve", league: "Premier League", badge: "New 26/27", slug: "liverpool-home-short-sleeve-2026-27", description: "Liverpool 2026-27 short-sleeve home jersey, inspired by the club's 1989-90 title-winning strip, with a red base, energetic white geometric graphics and white adidas detailing." },
].map(({ slug, ...kit }) => ({
  ...kit,
  price: 999,
  number: "Plain back",
  gradient: "from-[#111827] via-[#334155] to-[#f8fafc]",
  image: `/kits/2026-27/${slug}-front.webp`,
  backImage: `/kits/2026-27/${slug}-back.webp`,
  color: "",
  stock: 40,
  sizeStock: { ...TEXT_ONLY_SIZE_STOCK },
  customizationAvailable: false,
})) as Kit[]

const newClubDropKits: Kit[] = [
  ...imported2026DropKits,
  {
    id: 360, name: "Real Madrid Away 2026-27", club: "Real Madrid", season: "Away 2026-27 - short sleeve",
    price: 999, number: "Plain back", league: "La Liga", gradient: "from-[#003d36] via-[#0a6659] to-[#f8fafc]",
    badge: "New 26/27", image: "/kits/2026-27/real-madrid-away-2026-27-front.png", backImage: "/kits/2026-27/real-madrid-away-2026-27-back.png",
    color: "Forest green/white", stock: 40, sizeStock: { ...TEXT_ONLY_SIZE_STOCK },
    customizationAvailable: false,
    description: "Real Madrid 2026-27 away jersey in deep forest green with white adidas shoulder stripes, heritage Trefoil branding and a clean plain back.",
  },
  {
    id: 300, name: "Manchester United Home Jersey", club: "Manchester United", season: "Home 2026-27 - short sleeve",
    price: 1399, number: "Plain back", league: "Premier League", gradient: "from-[#d71920] via-[#8b1117] to-[#ffffff]",
    badge: "New Drop", image: "/kits/new-club-drop/manchester-united-2025-26-home-front.webp", backImage: "/kits/new-club-drop/manchester-united-2025-26-home-back.webp",
    color: "Red/white", stock: 40, sizeStock: { ...TEXT_ONLY_SIZE_STOCK },
    description: "Manchester United 2026-27 home jersey in classic red, with a small polo collar, white adidas shoulder stripes, Snapdragon sponsor and a clean plain back.",
  },
  {
    id: 301, name: "Juventus Gold Jeep Jersey", club: "Juventus", season: "Home 2026-27 - short sleeve",
    price: 1399, number: "Plain back", league: "Serie A", gradient: "from-[#111111] via-[#ffffff] to-[#b38b2e]",
    badge: "New Drop", image: "/kits/new-club-drop/juventus-gold-jeep-home-front.webp", backImage: "/kits/new-club-drop/juventus-gold-jeep-home-back.webp",
    color: "Black/white/gold", stock: 40, sizeStock: { ...TEXT_ONLY_SIZE_STOCK },
    description: "Juventus 2026-27 home jersey reworking the club's black-and-white stripes with geometric spacing, a heritage polo collar and refined gold detailing.",
  },
  {
    id: 302, name: "Real Madrid Black Originals Jersey", club: "Real Madrid", season: "Black Originals Edition - short sleeve",
    price: 1399, number: "Plain back", league: "La Liga", gradient: "from-[#080808] via-[#27272a] to-[#ffffff]",
    badge: "New Drop", image: "/kits/new-club-drop/real-madrid-black-originals-front.webp", backImage: "/kits/new-club-drop/real-madrid-black-originals-back.webp",
    color: "Black/white", stock: 40, sizeStock: { ...TEXT_ONLY_SIZE_STOCK },
    description: "Real Madrid Adidas Originals jersey in black with a tonal vertical texture, white Trefoil branding, club crest, Emirates Fly Better sponsor and a clean plain back.",
  },
  {
    id: 303, name: "Tottenham Black AIA Jersey", club: "Tottenham Hotspur", season: "Black Edition - short sleeve",
    price: 1399, number: "Plain back", league: "Premier League", gradient: "from-[#050505] via-[#27272a] to-[#f8fafc]",
    badge: "New Drop", image: "/kits/new-club-drop/tottenham-black-aia-front.webp", backImage: "/kits/new-club-drop/tottenham-black-aia-back.webp",
    color: "Black/white", stock: 40, sizeStock: { ...TEXT_ONLY_SIZE_STOCK },
    description: "Tottenham Hotspur 2025-26 away jersey, marking the club's return to an all-black change kit with a tonal grid, white Nike details and AIA sponsor.",
  },
  {
    id: 304, name: "Barcelona Orange Third Jersey", club: "FC Barcelona", season: "Orange Third 2025-26 - short sleeve",
    price: 1399, number: "Plain back", league: "La Liga", gradient: "from-[#ff5a36] via-[#ff7656] to-[#111827]",
    badge: "New Drop", image: "/kits/new-club-drop/barcelona-orange-third-front.webp", backImage: "/kits/new-club-drop/barcelona-orange-third-back.webp",
    color: "Fluorescent orange/navy", stock: 40, sizeStock: { ...TEXT_ONLY_SIZE_STOCK },
    description: "FC Barcelona 2025-26 third jersey in bright mango orange, created as a tribute to the historic 2009 sextuple-winning season.",
  },
  {
    id: 305, name: "Manchester United Third Jersey", club: "Manchester United", season: "Third 2025-26 - short sleeve",
    price: 1399, number: "Plain back", league: "Premier League", gradient: "from-[#050505] via-[#111827] to-[#facc15]",
    badge: "New Drop", image: "/kits/new-club-drop/manchester-united-black-originals-front.webp", backImage: "/kits/new-club-drop/manchester-united-black-originals-back.webp",
    color: "Black/yellow/blue", stock: 40, sizeStock: { ...TEXT_ONLY_SIZE_STOCK },
    description: "Manchester United 2025-26 third jersey inspired by the club's 1993-94 away look, combining a black base with yellow and blue accents, Trefoil branding and Snapdragon sponsor.",
  },
  {
    id: 306, name: "Barcelona Pastel Concept Jersey", club: "FC Barcelona", season: "Pastel Concept Kit - short sleeve",
    price: 1399, number: "Plain back", league: "La Liga", gradient: "from-[#f9a8d4] via-[#bef264] to-[#60a5fa]",
    badge: "Concept Kit", image: "/kits/new-club-drop/barcelona-pastel-concept-front.webp", backImage: "/kits/new-club-drop/barcelona-pastel-concept-back.webp",
    color: "Pastel pink/lime/blue", stock: 40, sizeStock: { ...TEXT_ONLY_SIZE_STOCK },
    description: "FC Barcelona concept jersey blending pastel blue, pink and lime panels with fine technical linework and a bold navy Spotify mark.",
  },
  {
    id: 307, name: "PSG Jordan Wings Jersey", club: "Paris Saint-Germain", season: "Jordan Wings 2024-25 - short sleeve",
    price: 1399, number: "Plain back", league: "Ligue 1", gradient: "from-[#0b2d5c] via-[#153e75] to-[#ffffff]",
    badge: "New Drop", image: "/kits/new-club-drop/psg-jordan-wings-front.webp", backImage: "/kits/new-club-drop/psg-jordan-wings-back.webp",
    color: "Deep navy/white", stock: 40, sizeStock: { ...TEXT_ONLY_SIZE_STOCK },
    description: "Paris Saint-Germain x Jordan Wings special-edition jersey in deep navy, with shoulder graphics drawn from the iconic Jordan Wings motif.",
  },
  {
    id: 308, name: "Arsenal Cream Originals Jersey", club: "Arsenal", season: "Cream Originals Edition - short sleeve",
    price: 1399, number: "Plain back", league: "Premier League", gradient: "from-[#fffdf5] via-[#f5f0e6] to-[#7f1d1d]",
    badge: "New Drop", image: "/kits/new-club-drop/arsenal-cream-originals-front.webp", backImage: "/kits/new-club-drop/arsenal-cream-originals-back.webp",
    color: "Cream/burgundy", stock: 40, sizeStock: { ...TEXT_ONLY_SIZE_STOCK },
    description: "Arsenal 2025-26 third jersey in an off-white heritage palette, with burgundy accents, a polo collar, Trefoil branding and the cannon crest.",
  },
  {
    id: 309, name: "AC Milan Home 2025-26", club: "AC Milan", season: "Home 2025-26 - short sleeve",
    price: 1399, number: "Plain back", league: "Serie A", gradient: "from-[#dc2626] via-[#111111] to-[#ffffff]",
    badge: "New Drop", image: "/kits/new-club-drop/ac-milan-red-black-home-front.webp", backImage: "/kits/new-club-drop/ac-milan-red-black-home-back.webp",
    color: "Red/black", stock: 40, sizeStock: { ...TEXT_ONLY_SIZE_STOCK },
    description: "AC Milan 2025-26 home jersey in the iconic Rossoneri red and black, with flame details worked through the stripes and a fiery red crest inspired by the club's historic devil symbol.",
  },
  {
    id: 310, name: "Liverpool Home 2025-26", club: "Liverpool", season: "Home 2025-26 - short sleeve",
    price: 1399, number: "Plain back", league: "Premier League", gradient: "from-[#dc151d] via-[#a40d16] to-[#ffffff]",
    badge: "New Drop", image: "/kits/new-club-drop/liverpool-red-home-front.webp", backImage: "/kits/new-club-drop/liverpool-red-home-back.webp",
    color: "Red/white", stock: 40, sizeStock: { ...TEXT_ONLY_SIZE_STOCK },
    description: "Liverpool 2025-26 home jersey in the club's traditional red, with white adidas shoulder stripes, white piping and the Standard Chartered sponsor.",
  },
  {
    id: 311, name: "Bayern Munich Third Jersey", club: "Bayern Munich", season: "Third 2025-26 - short sleeve",
    price: 1399, number: "Plain back", league: "Bundesliga", gradient: "from-[#050505] via-[#18181b] to-[#dc2626]",
    badge: "New Drop", image: "/kits/new-club-drop/bayern-black-originals-front.webp", backImage: "/kits/new-club-drop/bayern-black-originals-back.webp",
    color: "Black/white/red/green", stock: 40, sizeStock: { ...TEXT_ONLY_SIZE_STOCK },
    description: "Bayern Munich 2025-26 Champions League third jersey celebrating Munich heritage, with a black base, red, green and off-white accents, a historic 1920s club crest and Trefoil branding.",
  },
  {
    id: 312, name: "Barcelona Vintage Collar Concept Jersey", club: "FC Barcelona", season: "Vintage Collar Concept Kit - short sleeve",
    price: 1399, number: "Plain back", league: "La Liga", gradient: "from-[#8f1d38] via-[#173b6c] to-[#facc15]",
    badge: "Concept Kit", image: "/kits/new-club-drop/barcelona-vintage-collar-concept-front.webp", backImage: "/kits/new-club-drop/barcelona-vintage-collar-concept-back.webp",
    color: "Red/navy/yellow", stock: 40, sizeStock: { ...TEXT_ONLY_SIZE_STOCK },
    description: "FC Barcelona concept jersey combining vintage red-and-navy blocks, a classic fold-over collar and bright yellow club branding.",
  },
  {
    id: 313, name: "Juventus Pink Concept Jersey", club: "Juventus", season: "Pink Concept Kit - short sleeve",
    price: 1399, number: "Plain back", league: "Serie A", gradient: "from-[#111111] via-[#ffffff] to-[#f9a8d4]",
    badge: "Concept Kit", image: "/kits/new-club-drop/juventus-pink-concept-front.webp", backImage: "/kits/new-club-drop/juventus-pink-concept-back.webp",
    color: "Black/white/pink", stock: 40, sizeStock: { ...TEXT_ONLY_SIZE_STOCK },
    description: "Juventus concept jersey with asymmetric black-and-white striping, technical player-cut panels and bright pink crest and shoulder accents.",
  },
  {
    id: 314, name: "Chelsea Third Jersey", club: "Chelsea", season: "Third 2025-26 - short sleeve",
    price: 1399, number: "Plain back", league: "Premier League", gradient: "from-[#050505] via-[#111827] to-[#2563eb]",
    badge: "New Drop", image: "/kits/new-club-drop/chelsea-black-retro-front.webp", backImage: "/kits/new-club-drop/chelsea-black-retro-back.webp",
    color: "Black/white/blue", stock: 40, sizeStock: { ...TEXT_ONLY_SIZE_STOCK },
    description: "Chelsea 2025-26 third jersey reviving Nike's Total 90 look in black and silver, with royal-blue trim and the club's classic 1986-2005 crest.",
  },
  {
    id: 316, name: "Barcelona x Travis Scott Jersey", club: "FC Barcelona", season: "Travis Scott El Clasico 2024-25 - short sleeve",
    price: 1399, number: "Plain back", league: "La Liga", gradient: "from-[#050505] via-[#dc2626] to-[#2563eb]",
    badge: "Collaboration", image: "/kits/new-club-drop/barcelona-graffiti-concept-front.webp", backImage: "/kits/new-club-drop/barcelona-graffiti-concept-back.webp",
    color: "Black/red/blue", stock: 40, sizeStock: { ...TEXT_ONLY_SIZE_STOCK },
    description: "FC Barcelona x Travis Scott special El Clasico jersey, created with Spotify and carrying the artist's Cactus Jack logo across the chest.",
  },
  {
    id: 317, name: "Barcelona x Kobe Away Jersey", club: "FC Barcelona", season: "Away 2026-27 - short sleeve",
    price: 1399, number: "Plain back", league: "La Liga", gradient: "from-[#050505] via-[#312e81] to-[#7c3aed]",
    badge: "Collaboration", image: "/kits/new-club-drop/barcelona-kobe-gradient-concept-front.webp", backImage: "/kits/new-club-drop/barcelona-kobe-gradient-concept-back.webp",
    color: "Black/purple/gold", stock: 40, sizeStock: { ...TEXT_ONLY_SIZE_STOCK },
    description: "FC Barcelona x Kobe Bryant 2026-27 away jersey, combining a black-to-purple fade, snakeskin-inspired texture, Kobe branding and gold detailing.",
  },
  {
    id: 318, name: "Manchester United Home Retro Jersey", club: "Manchester United", season: "Home 1982-84 Retro - short sleeve",
    price: 1299, number: "Plain back", league: "Premier League", gradient: "from-[#dc151d] via-[#9f1239] to-[#ffffff]",
    badge: "Retro", image: "/kits/new-club-drop/manchester-united-red-pinstripe-retro-front.webp", backImage: "/kits/new-club-drop/manchester-united-red-pinstripe-retro-back.webp",
    color: "Red/white", stock: 40, sizeStock: { ...TEXT_ONLY_SIZE_STOCK },
    productType: "retro-player",
    description: "Manchester United 1982-84 home retro jersey in vivid red with fine white pinstripes, a polo collar, classic Trefoil and an understated sponsor-free finish.",
  },
  {
    id: 319, name: "Liverpool Third Jersey", club: "Liverpool", season: "Third 2025-26 - short sleeve",
    price: 1299, number: "Plain back", league: "Premier League", gradient: "from-[#0891b2] via-[#0f766e] to-[#ffffff]",
    badge: "New Drop", image: "/kits/new-club-drop/liverpool-teal-retro-front.webp", backImage: "/kits/new-club-drop/liverpool-teal-retro-back.webp",
    color: "Teal/white/black", stock: 40, sizeStock: { ...TEXT_ONLY_SIZE_STOCK },
    description: "Liverpool 2025-26 third jersey in sea green with fine pinstripes, black collar trim, white shoulder stripes, Trefoil branding and the heritage club crest last used in 1992.",
  },
  {
    id: 320, name: "Bayern Munich Home 2025-26", club: "Bayern Munich", season: "Home 2025-26 - short sleeve",
    price: 1399, number: "Plain back", league: "Bundesliga", gradient: "from-[#dc2626] via-[#ef4444] to-[#ffffff]",
    badge: "New Drop", image: "/kits/new-club-drop/bayern-red-home-2025-26-front.webp", backImage: "/kits/new-club-drop/bayern-red-home-2025-26-back.webp",
    color: "Red/white", stock: 40, sizeStock: { ...TEXT_ONLY_SIZE_STOCK },
    description: "Bayern Munich 2025-26 home jersey in the club's classic red and white, with a prominent stylised M across the front celebrating Munich and the club's roots in the Bavarian capital.",
  },
  {
    id: 321, name: "Chelsea Home Jersey", club: "Chelsea", season: "Home 2025-26 - short sleeve",
    price: 1399, number: "Plain back", league: "Premier League", gradient: "from-[#1d4ed8] via-[#2563eb] to-[#ffffff]",
    badge: "New Drop", image: "/kits/new-club-drop/chelsea-blue-home-2025-26-front.webp", backImage: "/kits/new-club-drop/chelsea-blue-home-2025-26-back.webp",
    color: "Royal blue/white", stock: 40, sizeStock: { ...TEXT_ONLY_SIZE_STOCK },
    description: "Chelsea home jersey in royal blue with a layered tonal geometric pattern, white V-neck insert and clean sponsor-free front.",
  },
  {
    id: 322, name: "Paris Saint-Germain Home 2025-26", club: "Paris Saint-Germain", season: "Home 2025-26 - short sleeve",
    price: 1399, number: "Plain back", league: "Ligue 1", gradient: "from-[#0f274d] via-[#1e3a8a] to-[#dc2626]",
    badge: "New Drop", image: "/kits/new-club-drop/psg-navy-home-2025-26-front.webp", backImage: "/kits/new-club-drop/psg-navy-home-2025-26-back.webp",
    color: "Navy/red/white", stock: 40, sizeStock: { ...TEXT_ONLY_SIZE_STOCK },
    description: "Paris Saint-Germain 2025-26 home jersey with a midnight-blue base, vibrant red-and-white accents and a lattice-inspired central graphic honouring the metal framework of Parisian architectural landmarks.",
  },
  {
    id: 323, name: "Inter Miami Riptide Third Jersey", club: "Inter Miami", season: "Riptide Third 2025 - short sleeve",
    price: 1399, number: "Plain back", league: "MLS", gradient: "from-[#7dd3fc] via-[#bae6fd] to-[#f9a8d4]",
    badge: "New Drop", image: "/kits/new-club-drop/inter-miami-light-blue-front.webp", backImage: "/kits/new-club-drop/inter-miami-light-blue-back.webp",
    color: "Light blue/pink/white", stock: 40, sizeStock: { ...TEXT_ONLY_SIZE_STOCK },
    description: "Inter Miami 2025 Riptide third jersey in Miami Blue with Miami Pink and white accents, Trefoil branding and the Royal Caribbean sponsor.",
  },
  {
    id: 324, name: "Manchester City Home Jersey", club: "Manchester City", season: "Home 2025-26 - short sleeve",
    price: 1399, number: "Plain back", league: "Premier League", gradient: "from-[#7dd3fc] via-[#38bdf8] to-[#ffffff]",
    badge: "New Drop", image: "/kits/new-club-drop/manchester-city-home-2025-26-front.webp", backImage: "/kits/new-club-drop/manchester-city-home-2025-26-back.webp",
    color: "Sky blue/white/navy", stock: 40, sizeStock: { ...TEXT_ONLY_SIZE_STOCK },
    description: "Manchester City sky-blue home jersey with a sharp diagonal white stripe, navy Puma and Etihad branding and lightweight performance panels.",
  },
  {
    id: 325, name: "Arsenal Blue Away Jersey", club: "Arsenal", season: "Away 2025-26 - short sleeve",
    price: 1399, number: "Plain back", league: "Premier League", gradient: "from-[#0f172a] via-[#1d4ed8] to-[#ef4444]",
    badge: "New Drop", image: "/kits/new-club-drop/arsenal-blue-away-2025-26-front.webp", backImage: "/kits/new-club-drop/arsenal-blue-away-2025-26-back.webp",
    color: "Navy/electric blue/red", stock: 40, sizeStock: { ...TEXT_ONLY_SIZE_STOCK },
    description: "Arsenal away jersey in navy and electric blue with an all-over lightning pattern, red shoulder stripes and white cannon and sponsor marks.",
  },
  {
    id: 326, name: "Real Madrid Home Jersey", club: "Real Madrid", season: "Home 2026-27 - short sleeve",
    price: 1399, number: "Plain back", league: "La Liga", gradient: "from-[#ffffff] via-[#f8fafc] to-[#be123c]",
    badge: "New 26/27", image: "/kits/2026-27/real-madrid-home-2026-27-front.webp", backImage: "/kits/2026-27/real-madrid-home-2026-27-back.webp",
    color: "White/black/pink-red", stock: 40, sizeStock: { ...TEXT_ONLY_SIZE_STOCK },
    description: "Real Madrid 2026-27 home jersey with a crisp white performance-knit base, black collar and sleeve cuffs, pink-red adidas shoulder stripes, the club crest and Emirates Fly Better sponsor. Supplied with a clean plain back.",
  },
].map((kit) => ({
  ...kit,
  name: NEW_CLUB_DROP_NAMES[kit.id] || kit.name,
  season: kit.badge === "Concept Kit"
    ? "Concept 2026-27"
    : String(kit.season).replace(" - short sleeve", ""),
  price: 999,
  color: "",
  customizationAvailable: false,
}))

// These extra products came with the supplied project archive.  They are kept
// alongside (rather than in place of) the current catalogue so that none of
// the verified front/back jersey photos are lost.
const suppliedArchiveKits: Kit[] = [
  ...[
    ["Chelsea", "Chelsea Track Jacket", "Black/blue track jacket", "Premier League", "Black with electric blue panels", "chelsea-black-blue-track-jacket.webp"],
    ["AC Milan", "AC Milan Track Jacket", "Black/red track jacket", "Serie A", "Black with red panels", "ac-milan-black-red-track-jacket.webp"],
    ["Borussia Dortmund", "Borussia Dortmund Track Jacket", "Black/yellow track jacket", "Bundesliga", "Black with yellow panels", "borussia-dortmund-black-yellow-track-jacket.webp"],
    ["Germany", "Germany Track Jacket", "White retro track jacket", "International", "White with red, black and gold accents", "germany-white-track-jacket.webp"],
    ["Manchester City", "Manchester City Track Jacket", "Navy/sky blue track jacket", "Premier League", "Navy with sky blue panels", "manchester-city-navy-blue-track-jacket.webp"],
    ["Real Madrid", "Real Madrid Track Jacket", "Navy/orange track jacket", "La Liga", "Navy with orange details", "real-madrid-navy-orange-track-jacket.webp"],
  ].map(([club, name, season, league, color, file], index) => ({
    id: 1001 + index,
    name,
    club,
    season,
    price: 1299,
    number: "Jacket",
    league,
    gradient: "from-[#111827] via-[#334155] to-[#f8fafc]",
    badge: "Jacket",
    image: `/kits/supplied-drops/new/${file}`,
    backImage: `/kits/supplied-drops/new/${file}`,
    color,
    stock: 40,
    sizeStock: { ...TEXT_ONLY_SIZE_STOCK },
    productType: "jacket" as const,
    customizationAvailable: false,
  })),
  ...[
    ["Tottenham Hotspur", "Black 2026-27", "Black/grey Spurs home", "tottenham-black-2026-27.webp"],
    ["Arsenal", "Home 2026-27", "White with maroon details", "arsenal-home-2026-27.webp"],
    ["Real Madrid", "Black 2026-27", "Black with white adidas details", "real-madrid-black-2026-27.webp"],
    ["Paris Saint-Germain", "Navy 2026-27", "Navy with white details", "psg-navy-2026-27.webp"],
    ["Barcelona", "Blue/pink 2026-27", "Light blue and pink", "barcelona-blue-pink-2026-27.webp"],
    ["Paris Saint-Germain", "Home 2025-26", "Navy with red centre stripe", "psg-home-2025-26.webp"],
    ["Barcelona", "Pink 2026-27", "Pink with tonal details", "barcelona-pink-2026-27.webp"],
    ["Real Madrid", "Home 2026-27", "White with black and gold details", "real-madrid-home-2026-27.webp"],
    ["Barcelona", "Black 2026-27", "Black with red and blue side panels", "barcelona-black-2026-27.webp"],
    ["Barcelona", "Blue/red 2026-27", "Blue and red stripes", "barcelona-blue-red-2026-27.webp"],
    ["Manchester City", "Home 2026-27", "White with blue centre stripes", "manchester-city-home-2026-27.webp"],
    ["AC Milan", "Black/red 2026-27", "Black with red details", "ac-milan-black-red-2026-27.webp"],
    ["Paris Saint-Germain", "Home 2026-27", "Blue and red centre stripe", "psg-home-2026-27.webp"],
    ["Bayern Munich", "Home 2026-27", "Red with tonal stripes", "bayern-home-2026-27.webp"],
    ["Tottenham Hotspur", "Home 2026-27", "White home jersey", "tottenham-home-2026-27.webp"],
    ["Manchester City", "Home Sky Blue 2026-27", "Sky blue home jersey", "manchester-city-home-sky-2026-27.webp"],
    ["Liverpool", "Home 2026-27", "Red with white details", "liverpool-home-2026-27.webp"],
  ].map(([club, season, color, file], index) => ({
    id: 1007 + index,
    name: `${club} Jersey`,
    club,
    season: `${season} - short sleeve`,
    price: 1399,
    number: "#10",
    league: "Club Football",
    gradient: "from-[#111111] via-[#1d4ed8] to-[#ef4444]",
    badge: "New Drop",
    image: `/kits/supplied-drops/new/${file}`,
    backImage: `/kits/supplied-drops/new/${file}`,
    color,
    stock: 40,
    sizeStock: { ...TEXT_ONLY_SIZE_STOCK },
    customizationAvailable: false,
  })),
  ...[
    ["Real Madrid", "Home 1999-2000 Retro", "White with black and gold details", "real-madrid-home-1999-2000-retro.webp"],
    ["Germany", "Home 2005-06 Retro", "White with black, red and gold details", "germany-home-2005-06-retro.webp"],
    ["Manchester United", "Black AIG 2008-09 Retro", "Black with red details", "manchester-united-black-aig-2008-09-retro.webp"],
    ["Brazil", "Home 1998-99 Retro", "Yellow and green classic", "brazil-home-1998-99-retro.webp"],
    ["Manchester United", "Away 2013-14 Retro", "Blue and black checked", "manchester-united-away-2013-14-retro.webp"],
    ["Liverpool", "Home Carlsberg Retro", "Red with white adidas details", "liverpool-home-carlsberg-retro.webp"],
    ["Argentina", "Away 1994-95 Retro", "Blue with geometric pattern", "argentina-away-1994-95-retro.webp"],
    ["Manchester United", "Blue 1990s Retro", "Blue geometric pattern", "manchester-united-blue-1990s-retro.webp"],
    ["AC Milan", "Graphic Retro", "Black graphic print", "ac-milan-graphic-retro.webp"],
    ["Manchester United", "Home 1998-99 Retro", "Red with black and white details", "manchester-united-home-1998-99-retro.webp"],
    ["Manchester United", "Home 1999 Retro", "Red Champions League style", "manchester-united-home-1999-retro.webp"],
    ["Barcelona", "Home Retro", "Blue and red stripes", "barcelona-home-retro.webp"],
    ["Juventus", "Black/white Gold Retro", "Black and white stripes", "juventus-black-white-gold-retro.webp"],
    ["Celtic", "Green/white Retro", "Green and white hoops", "celtic-green-white-retro.webp"],
  ].map(([club, season, color, file], index) => ({
    id: 1024 + index,
    name: `${club} Jersey`,
    club,
    season: `${season} - short sleeve`,
    price: 1399,
    number: "Retro",
    league: "Club Football",
    gradient: "from-[#111111] via-[#dc2626] to-[#f8fafc]",
    badge: "Retro",
    image: `/kits/supplied-drops/retro/${file}`,
    backImage: `/kits/supplied-drops/retro/${file}`,
    color,
    stock: 40,
    sizeStock: { ...TEXT_ONLY_SIZE_STOCK },
    customizationAvailable: false,
  })),
]

const baseKits: Kit[] = [
  {
    id: 1,
    name: "Cristiano Ronaldo",
    club: "Portugal",
    season: "Home 2026 - short sleeve",
    price: 1499,
    number: "#7",
    league: "International",
    gradient: "from-[#c1121f] via-[#0b7a3b] to-[#f7f7f2]",
    badge: "26 World Cup",
    image: "/kits/portugal-2026-home-ronaldo-front.webp",
    color: "Red/green modern split",
    stock: 40,
    sizeStock: {
      S: 10,
      M: 10,
      L: 10,
      XL: 10
    },
    backImage: "/kits/portugal-2026-home-ronaldo-back.webp"
  },
  {
    id: 2,
    name: "Cristiano Ronaldo",
    club: "Portugal",
    season: "Away 2026 - short sleeve",
    price: 1499,
    number: "#7",
    league: "International",
    gradient: "from-[#0f766e] via-[#5eead4] to-[#0b1320]",
    badge: "26 World Cup",
    image: "/kits/remade/portugal-2026-away-ronaldo-front.jpg",
    color: "Teal wave design",
    stock: 40,
    sizeStock: {
      S: 10,
      M: 10,
      L: 10,
      XL: 10
    },
    backImage: "/kits/remade/portugal-2026-away-ronaldo-back.jpg"
  },
  {
    id: 3,
    name: "Cristiano Ronaldo",
    club: "Portugal",
    season: "3rd kit 2026 - short sleeve",
    price: 1499,
    number: "#7",
    league: "International",
    gradient: "from-[#111111] via-[#3f3f46] to-[#d4af37]",
    badge: "26 World Cup",
    image: "/kits/portugal-2026-third-ronaldo-front.webp",
    color: "Black with gold",
    stock: 40,
    sizeStock: {
      S: 10,
      M: 10,
      L: 10,
      XL: 10
    },
    backImage: "/kits/portugal-2026-third-ronaldo-back.png"
  },
  {
    id: 4,
    name: "Lamine Yamal",
    club: "Spain",
    season: "Home 2026 - short sleeve",
    price: 1499,
    number: "#19",
    league: "International",
    gradient: "from-[#c1121f] via-[#7f1d1d] to-[#facc15]",
    badge: "26 World Cup",
    image: "/kits/processed/standardized-source/source-15-single.webp",
    color: "Red modern clean",
    stock: 40,
    sizeStock: {
      S: 10,
      M: 10,
      L: 10,
      XL: 10
    },
    backImage: "/kits/processed/spain-2026-home-back.webp"
  },
  {
    id: 5,
    name: "Lamine Yamal",
    club: "Spain",
    season: "Away 2026 - short sleeve",
    price: 1499,
    number: "#19",
    league: "International",
    gradient: "from-[#facc15] via-[#166534] to-[#ffffff]",
    badge: "26 World Cup",
    image: "/kits/processed/spain-2026-away-front.webp",
    color: "Gold/yellow experimental",
    stock: 40,
    sizeStock: {
      S: 10,
      M: 10,
      L: 10,
      XL: 10
    },
    backImage: "/kits/remade/spain-2026-away-yamal-back.jpg"
  },
  {
    id: 6,
    name: "Kylian Mbappe",
    club: "France",
    season: "Home 2026 - short sleeve",
    price: 1499,
    number: "#10",
    league: "International",
    gradient: "from-[#f8fafc] via-[#1d4ed8] to-[#111827]",
    badge: "26 World Cup",
    image: "/kits/remade/france-2026-home-mbappe-front.jpg",
    color: "Royal blue geometric design",
    stock: 40,
    sizeStock: {
      S: 10,
      M: 10,
      L: 10,
      XL: 10
    },
    backImage: "/kits/remade/france-2026-home-mbappe-back.jpg"
  },
  {
    id: 7,
    name: "Kylian Mbappe",
    club: "France",
    season: "Away 2026 - short sleeve",
    price: 1499,
    number: "#10",
    league: "International",
    gradient: "from-[#15803d] via-[#bbf7d0] to-[#111827]",
    badge: "26 World Cup",
    image: "/kits/remade/france-2026-away-mbappe-front.jpg",
    color: "Pale mint-white with tricolor trim",
    stock: 40,
    sizeStock: {
      S: 10,
      M: 10,
      L: 10,
      XL: 10
    },
    backImage: "/kits/remade/france-2026-away-mbappe-back.jpg"
  },
  {
    id: 8,
    name: "Neymar Jr.",
    club: "Brazil",
    season: "Home 2026 - short sleeve",
    price: 1499,
    number: "#10",
    league: "International",
    gradient: "from-[#facc15] via-[#166534] to-[#ffffff]",
    badge: "26 World Cup",
    image: "/kits/processed/brazil-2026/brazil-home-2026-front.png",
    color: "Yellow/green classic",
    description: "Neymar Jr. brings Brazilian flair, creativity, and iconic number 10 energy to the Brazil Home 2026 jersey, carrying the tradition of Brazil's famous yellow and green shirt.",
    stock: 40,
    sizeStock: {
      S: 10,
      M: 10,
      L: 10,
      XL: 10
    },
    backImage: "/kits/processed/brazil-2026/brazil-home-2026-back.png"
  },
  {
    id: 9,
    name: "Neymar Jr.",
    club: "Brazil",
    season: "Away 2026 - short sleeve",
    price: 1499,
    number: "#10",
    league: "International",
    gradient: "from-[#0f172a] via-[#1d4ed8] to-[#ef4444]",
    badge: "26 World Cup",
    image: "/kits/processed/brazil-2026/brazil-away-2026-front.png",
    color: "Dark navy modern pattern",
    description: "Neymar Jr. brings Brazilian flair, creativity, and iconic number 10 energy to the Brazil Away 2026 jersey, representing the skill and confidence that made him one of his generation's most exciting players.",
    stock: 40,
    sizeStock: {
      S: 10,
      M: 10,
      L: 10,
      XL: 10
    },
    backImage: "/kits/processed/brazil-2026/brazil-away-2026-back.png"
  },
  {
    id: 10,
    name: "Lionel Messi",
    club: "Argentina",
    season: "Home 2026 - short sleeve",
    price: 1499,
    number: "#10",
    league: "International",
    gradient: "from-[#f8fafc] via-[#1d4ed8] to-[#111827]",
    badge: "26 World Cup",
    image: "/kits/processed/argentina-home-2026-clean-front.webp",
    color: "Sky blue/white stripes",
    stock: 40,
    sizeStock: {
      S: 10,
      M: 10,
      L: 10,
      XL: 10
    },
    backImage: "/kits/processed/argentina-home-2026-clean-back.webp"
  },
  {
    id: 11,
    name: "Lionel Messi",
    club: "Argentina",
    season: "Away 2026 - short sleeve",
    price: 1499,
    number: "#10",
    league: "International",
    gradient: "from-[#0f172a] via-[#1d4ed8] to-[#ef4444]",
    badge: "26 World Cup",
    image: "/kits/processed/argentina-away-2026-messi-black-upscaled.png",
    color: "Dark blue gradient",
    stock: 40,
    sizeStock: {
      S: 10,
      M: 10,
      L: 10,
      XL: 10
    },
    backImage: "/kits/processed/argentina-away-2026-messi-black-upscaled.png"
  },
  {
    id: 12,
    name: "Jude Bellingham",
    club: "England",
    season: "Home 2026 - short sleeve",
    price: 1499,
    number: "#10",
    league: "International",
    gradient: "from-[#f8fafc] via-[#1d4ed8] to-[#111827]",
    badge: "26 World Cup",
    image: "/placeholder.svg",
    color: "White/navy classic clean",
    stock: 40,
    sizeStock: {
      S: 10,
      M: 10,
      L: 10,
      XL: 10
    },
    backImage: "/placeholder.svg",
    isDraft: true
  },
  {
    id: 13,
    name: "Jude Bellingham",
    club: "England",
    season: "Away 2026 - short sleeve",
    price: 1499,
    number: "#10",
    league: "International",
    gradient: "from-[#c1121f] via-[#7f1d1d] to-[#facc15]",
    badge: "26 World Cup",
    image: "/placeholder.svg",
    color: "Red modern pattern",
    stock: 40,
    sizeStock: {
      S: 10,
      M: 10,
      L: 10,
      XL: 10
    },
    backImage: "/placeholder.svg",
    isDraft: true
  },
  {
    id: 14,
    name: "Jamal Musiala",
    club: "Germany",
    season: "Home 2026 - short sleeve",
    price: 1499,
    number: "#10",
    league: "International",
    gradient: "from-[#111111] via-[#3f3f46] to-[#d4af37]",
    badge: "26 World Cup",
    image: "/placeholder.svg",
    color: "White/black retro style",
    stock: 40,
    sizeStock: {
      S: 10,
      M: 10,
      L: 10,
      XL: 10
    },
    backImage: "/placeholder.svg",
    isDraft: true
  },
  {
    id: 15,
    name: "Jamal Musiala",
    club: "Germany",
    season: "Away 2026 - short sleeve",
    price: 1499,
    number: "#10",
    league: "International",
    gradient: "from-[#111111] via-[#3f3f46] to-[#d4af37]",
    badge: "26 World Cup",
    image: "/placeholder.svg",
    color: "Black/grey modern design",
    stock: 40,
    sizeStock: {
      S: 10,
      M: 10,
      L: 10,
      XL: 10
    },
    backImage: "/placeholder.svg",
    isDraft: true
  },
  {
    id: 16,
    name: "Christian Pulisic",
    club: "USA",
    season: "Home 2026 - short sleeve",
    price: 1499,
    number: "#10",
    league: "International",
    gradient: "from-[#f8fafc] via-[#1d4ed8] to-[#111827]",
    badge: "26 World Cup",
    image: "/placeholder.svg",
    color: "White/red/navy stars design",
    stock: 40,
    sizeStock: {
      S: 10,
      M: 10,
      L: 10,
      XL: 10
    },
    backImage: "/placeholder.svg",
    isDraft: true
  },
  {
    id: 17,
    name: "Weston McKennie",
    club: "USA",
    season: "Away 2026 - short sleeve",
    price: 1499,
    number: "#8",
    league: "International",
    gradient: "from-[#0f172a] via-[#1d4ed8] to-[#ef4444]",
    badge: "26 World Cup",
    image: "/placeholder.svg",
    color: "Dark navy star pattern",
    stock: 40,
    sizeStock: {
      S: 10,
      M: 10,
      L: 10,
      XL: 10
    },
    backImage: "/placeholder.svg",
    isDraft: true
  },
  {
    id: 18,
    name: "Hirving Lozano",
    club: "Mexico",
    season: "Home 2026 - short sleeve",
    price: 1499,
    number: "#22",
    league: "International",
    gradient: "from-[#15803d] via-[#bbf7d0] to-[#111827]",
    badge: "26 World Cup",
    image: "/placeholder.svg",
    color: "Green classic modern",
    stock: 40,
    sizeStock: {
      S: 10,
      M: 10,
      L: 10,
      XL: 10
    },
    backImage: "/placeholder.svg",
    isDraft: true
  },
  {
    id: 19,
    name: "Santiago Gimenez",
    club: "Mexico",
    season: "Away 2026 - short sleeve",
    price: 1499,
    number: "#11",
    league: "International",
    gradient: "from-[#111111] via-[#3f3f46] to-[#d4af37]",
    badge: "26 World Cup",
    image: "/placeholder.svg",
    color: "Red/black Aztec style",
    stock: 40,
    sizeStock: {
      S: 10,
      M: 10,
      L: 10,
      XL: 10
    },
    backImage: "/placeholder.svg",
    isDraft: true
  },
  {
    id: 20,
    name: "Cristiano Ronaldo",
    club: "Real Madrid",
    season: "Home 2014-15 - short sleeve",
    price: 1399,
    number: "#7",
    league: "La Liga",
    gradient: "from-[#facc15] via-[#166534] to-[#ffffff]",
    badge: "Player Pick",
    image: "/kits/processed/may30/kit-41-front.png",
    color: "White/gold classic",
    stock: 40,
    sizeStock: {
      S: 10,
      M: 10,
      L: 10,
      XL: 10
    },
    backImage: "/kits/processed/may30/kit-41-back.png"
  },
  {
    id: 21,
    name: "Cristiano Ronaldo",
    club: "Real Madrid",
    season: "Away 2017-18 - short sleeve",
    price: 1399,
    number: "#7",
    league: "La Liga",
    gradient: "from-[#0f766e] via-[#5eead4] to-[#0b1320]",
    badge: "Player Pick",
    image: "/kits/processed/may30/kit-50-front.png",
    color: "Blue/teal away",
    stock: 40,
    sizeStock: {
      S: 10,
      M: 10,
      L: 10,
      XL: 10
    },
    backImage: "/kits/processed/may30/kit-50-back.png"
  },
  {
    id: 22,
    name: "Cristiano Ronaldo",
    club: "Juventus",
    season: "Away 2019-20 - short sleeve",
    price: 1399,
    number: "#7",
    league: "Serie A",
    gradient: "from-[#f9a8d4] via-[#111827] to-[#bbf7d0]",
    badge: "Player Pick",
    image: "/kits/processed/may30/kit-22-front.png",
    color: "Pink away",
    stock: 40,
    sizeStock: {
      S: 10,
      M: 10,
      L: 10,
      XL: 10
    },
    backImage: "/kits/processed/may30/kit-22-back.png"
  },
  {
    id: 23,
    name: "Cristiano Ronaldo",
    club: "Real Madrid",
    season: "Away 2016-17 - short sleeve",
    price: 1399,
    number: "#7",
    league: "La Liga",
    gradient: "from-[#1f2937] via-[#64748b] to-[#f8fafc]",
    badge: "Player Pick",
    image: "/kits/processed/may30/kit-53-front.png",
    color: "Purple away",
    stock: 40,
    sizeStock: {
      S: 10,
      M: 10,
      L: 10,
      XL: 10
    },
    backImage: "/kits/processed/may30/kit-53-back.png"
  },
  {
    id: 24,
    name: "Cristiano Ronaldo",
    club: "Real Madrid",
    season: "Home 2011-12 - long sleeve",
    price: 1499,
    number: "#7",
    league: "La Liga",
    gradient: "from-[#facc15] via-[#166534] to-[#ffffff]",
    badge: "Player Pick",
    image: "/kits/processed/may30/kit-42-front.png",
    color: "White/gold classic",
    stock: 40,
    sizeStock: {
      S: 10,
      M: 10,
      L: 10,
      XL: 10
    },
    backImage: "/kits/processed/may30/kit-42-back.png"
  },
  {
    id: 25,
    name: "Cristiano Ronaldo",
    club: "Portugal",
    season: "Home 2004 - short sleeve",
    price: 1399,
    number: "#17",
    league: "International",
    gradient: "from-[#c1121f] via-[#0b7a3b] to-[#f7f7f2]",
    badge: "Player Pick",
    image: "/placeholder.svg",
    color: "Red/green classic",
    stock: 40,
    sizeStock: {
      S: 10,
      M: 10,
      L: 10,
      XL: 10
    },
    backImage: "/placeholder.svg",
    isDraft: true
  },
  {
    id: 26,
    name: "Cristiano Ronaldo",
    club: "Manchester United",
    season: "Home 2007-08 - long sleeve",
    price: 1499,
    number: "#7",
    league: "Premier League",
    gradient: "from-[#c1121f] via-[#7f1d1d] to-[#facc15]",
    badge: "Player Pick",
    image: "/kits/kit-2-front.jpg",
    color: "Red classic",
    stock: 40,
    sizeStock: {
      S: 10,
      M: 10,
      L: 10,
      XL: 10
    },
    backImage: "/kits/kit-2-back.jpg"
  },
  {
    id: 27,
    name: "Cristiano Ronaldo",
    club: "Manchester United",
    season: "Away 2007-08 - short sleeve",
    price: 1399,
    number: "#7",
    league: "Premier League",
    gradient: "from-[#111111] via-[#3f3f46] to-[#d4af37]",
    badge: "Player Pick",
    image: "/kits/kit-2-front.jpg",
    color: "Black away",
    stock: 40,
    sizeStock: {
      S: 10,
      M: 10,
      L: 10,
      XL: 10
    },
    backImage: "/kits/kit-2-back.jpg"
  },
  {
    id: 28,
    name: "Cristiano Ronaldo",
    club: "Manchester United",
    season: "Away 2008-09 - short sleeve",
    price: 1399,
    number: "#7",
    league: "Premier League",
    gradient: "from-[#0f172a] via-[#1d4ed8] to-[#ef4444]",
    badge: "Player Pick",
    image: "/kits/kit-2-front.jpg",
    color: "Dark blue away",
    stock: 40,
    sizeStock: {
      S: 10,
      M: 10,
      L: 10,
      XL: 10
    },
    backImage: "/kits/kit-2-back.jpg"
  },
  {
    id: 29,
    name: "Cristiano Ronaldo",
    club: "Juventus FC",
    season: "Home 2019-20 - short sleeve",
    price: 1399,
    number: "#7",
    league: "Serie A",
    gradient: "from-[#111111] via-[#3f3f46] to-[#d4af37]",
    badge: "Player Pick",
    image: "/kits/processed/may30/kit-22-front.png",
    color: "Black/white stripes",
    stock: 40,
    sizeStock: {
      S: 10,
      M: 10,
      L: 10,
      XL: 10
    },
    backImage: "/kits/processed/may30/kit-22-back.png"
  },
  {
    id: 30,
    name: "Cristiano Ronaldo",
    club: "Al Nassr FC",
    season: "Home 2023-24 - short sleeve",
    price: 1399,
    number: "#7",
    league: "Saudi Pro League",
    gradient: "from-[#facc15] via-[#166534] to-[#ffffff]",
    badge: "Player Pick",
    image: "/kits/processed/may30/kit-40-front.png",
    color: "Yellow/blue home",
    stock: 40,
    sizeStock: {
      S: 10,
      M: 10,
      L: 10,
      XL: 10
    },
    backImage: "/kits/processed/may30/kit-40-back.png"
  },
  {
    id: 31,
    name: "Lionel Messi",
    club: "Barcelona",
    season: "Home 2010-11 - short sleeve",
    price: 1399,
    number: "#10",
    league: "La Liga",
    gradient: "from-[#0f172a] via-[#1d4ed8] to-[#ef4444]",
    badge: "Player Pick",
    image: "/kits/processed/may30/kit-33-front.png",
    color: "Blue/red stripes",
    stock: 40,
    sizeStock: {
      S: 10,
      M: 10,
      L: 10,
      XL: 10
    },
    backImage: "/kits/processed/may30/kit-33-back.png"
  },
  {
    id: 32,
    name: "Lionel Messi",
    club: "Argentina",
    season: "Home 2022 - short sleeve",
    price: 1399,
    number: "#10",
    league: "International",
    gradient: "from-[#f8fafc] via-[#1d4ed8] to-[#111827]",
    badge: "Player Pick",
    image: "/kits/processed/messi-argentina-2022-front.png",
    color: "Sky blue/white stripes",
    stock: 40,
    sizeStock: {
      S: 10,
      M: 10,
      L: 10,
      XL: 10
    },
    backImage: "/kits/processed/messi-argentina-2022-back.png",
    description: "Argentina 2022 home jersey for Lionel Messi, featuring the sky blue and white World Cup stripes, black shoulder trim, match-style sleeve patches, and Messi #10 on the back."
  },
  {
    id: 33,
    name: "Lionel Messi",
    club: "FC Barcelona",
    season: "Home 2014-15 - short sleeve",
    price: 1399,
    number: "#10",
    league: "La Liga",
    gradient: "from-[#0f172a] via-[#1d4ed8] to-[#ef4444]",
    badge: "Player Pick",
    image: "/kits/processed/may30/kit-33-front.png",
    color: "Blue/red hoops",
    stock: 40,
    sizeStock: {
      S: 10,
      M: 10,
      L: 10,
      XL: 10
    },
    backImage: "/kits/processed/may30/kit-33-back.png"
  },
  {
    id: 34,
    name: "Lionel Messi",
    club: "Paris Saint-Germain",
    season: "Home 2021-22 - short sleeve",
    price: 1399,
    number: "#30",
    league: "Ligue 1",
    gradient: "from-[#0f172a] via-[#1d4ed8] to-[#ef4444]",
    badge: "Player Pick",
    image: "/kits/processed/may30/kit-34-front.png",
    color: "Navy/red home",
    stock: 40,
    sizeStock: {
      S: 10,
      M: 10,
      L: 10,
      XL: 10
    },
    backImage: "/kits/processed/may30/kit-34-back.png"
  },
  {
    id: 35,
    name: "Lionel Messi",
    club: "Inter Miami CF",
    season: "Home 2023-24 - short sleeve",
    price: 1399,
    number: "#10",
    league: "MLS",
    gradient: "from-[#f9a8d4] via-[#111827] to-[#bbf7d0]",
    badge: "Player Pick",
    image: "/kits/processed/may30-fixes/kit-35-front.png",
    color: "Pink home",
    stock: 40,
    sizeStock: {
      S: 10,
      M: 10,
      L: 10,
      XL: 10
    },
    backImage: "/kits/processed/may30-fixes/kit-35-back.png"
  },
  {
    id: 36,
    name: "Neymar Jr.",
    club: "Santos",
    season: "Home 2011-12 - short sleeve",
    price: 599,
    number: "#11",
    league: "La Liga",
    gradient: "from-[#f8fafc] via-[#1d4ed8] to-[#111827]",
    badge: "Embroidery",
    productType: "embroidery",
    image: "/kits/processed/may30/kit-36-front.png",
    color: "White home",
    stock: 40,
    sizeStock: {
      S: 10,
      M: 10,
      L: 10,
      XL: 10
    },
    backImage: "/kits/processed/may30/kit-36-back.png"
  },
  {
    id: 37,
    name: "Neymar Jr.",
    club: "Barcelona",
    season: "Home 2014-15 - short sleeve",
    price: 1399,
    number: "#11",
    league: "La Liga",
    gradient: "from-[#0f172a] via-[#1d4ed8] to-[#ef4444]",
    badge: null,
    image: "/kits/processed/may30/kit-37-front.png",
    color: "Blue/red home",
    stock: 40,
    sizeStock: {
      S: 10,
      M: 10,
      L: 10,
      XL: 10
    },
    backImage: "/kits/processed/may30/kit-37-back.png"
  },
  {
    id: 38,
    name: "Neymar Jr.",
    club: "Brazil",
    season: "Home 2014 - short sleeve",
    price: 1399,
    number: "#10",
    league: "International",
    gradient: "from-[#facc15] via-[#166534] to-[#ffffff]",
    badge: null,
    image: "/kits/processed/may30/kit-38-front.png",
    color: "Yellow/green World Cup",
    stock: 40,
    sizeStock: {
      S: 10,
      M: 10,
      L: 10,
      XL: 10
    },
    backImage: "/kits/processed/may30/kit-38-back.png"
  },
  {
    id: 39,
    name: "Neymar Jr.",
    club: "Paris Saint-Germain",
    season: "Home 2017-18 - short sleeve",
    price: 1399,
    number: "#10",
    league: "Ligue 1",
    gradient: "from-[#0f172a] via-[#1d4ed8] to-[#ef4444]",
    badge: null,
    image: "/kits/processed/may30/kit-39-front.png",
    color: "Navy/red home",
    stock: 40,
    sizeStock: {
      S: 10,
      M: 10,
      L: 10,
      XL: 10
    },
    backImage: "/kits/processed/may30/kit-39-back.png"
  },
  {
    id: 40,
    name: "Neymar Jr.",
    club: "Al Hilal SFC",
    season: "Home 2023-24 - short sleeve",
    price: 1399,
    number: "#10",
    league: "Saudi Pro League",
    gradient: "from-[#0f172a] via-[#1d4ed8] to-[#ef4444]",
    badge: null,
    image: "/kits/processed/may30/kit-40-front.png",
    color: "Blue home",
    stock: 40,
    sizeStock: {
      S: 10,
      M: 10,
      L: 10,
      XL: 10
    },
    backImage: "/kits/processed/may30/kit-40-back.png"
  },
  {
    id: 41,
    name: "Karim Benzema",
    club: "Real Madrid",
    season: "Home 2021-22 - short sleeve",
    price: 1399,
    number: "#9",
    league: "La Liga",
    gradient: "from-[#facc15] via-[#166534] to-[#ffffff]",
    badge: null,
    image: "/kits/processed/may30/kit-41-front.png",
    color: "White/gold home",
    stock: 40,
    sizeStock: {
      S: 10,
      M: 10,
      L: 10,
      XL: 10
    },
    backImage: "/kits/processed/may30/kit-41-back.png"
  },
  {
    id: 42,
    name: "Luka Modric",
    club: "Real Madrid",
    season: "Home 2016-17 - long sleeve",
    price: 1499,
    number: "#10",
    league: "La Liga",
    gradient: "from-[#f8fafc] via-[#1d4ed8] to-[#111827]",
    badge: null,
    image: "/kits/processed/may30/kit-42-front.png",
    color: "White/purple home",
    stock: 40,
    sizeStock: {
      S: 10,
      M: 10,
      L: 10,
      XL: 10
    },
    backImage: "/kits/processed/may30/kit-42-back.png"
  },
  {
    id: 43,
    name: "Luka Modric",
    club: "Tottenham Hotspur",
    season: "Home 2010-11 - short sleeve",
    price: 1399,
    number: "#14",
    league: "Premier League",
    gradient: "from-[#f8fafc] via-[#1d4ed8] to-[#111827]",
    badge: null,
    image: "/kits/processed/may30/kit-43-front.png",
    color: "White/navy home",
    stock: 40,
    sizeStock: {
      S: 10,
      M: 10,
      L: 10,
      XL: 10
    },
    backImage: "/kits/processed/may30/kit-43-back.png"
  },
  {
    id: 44,
    name: "Kylian Mbappe",
    club: "Paris Saint-Germain",
    season: "Home 2017-18 - short sleeve",
    price: 1399,
    number: "#29",
    league: "Ligue 1",
    gradient: "from-[#0f172a] via-[#1d4ed8] to-[#ef4444]",
    badge: "Player Pick",
    image: "/kits/processed/may30/kit-44-front.png",
    color: "Dark navy/red",
    stock: 40,
    sizeStock: {
      S: 10,
      M: 10,
      L: 10,
      XL: 10
    },
    backImage: "/kits/processed/may30/kit-44-back.png"
  },
  {
    id: 45,
    name: "Kylian Mbappe",
    club: "Paris Saint-Germain",
    season: "Home 2018-19 - short sleeve",
    price: 1399,
    number: "#7",
    league: "Ligue 1",
    gradient: "from-[#0f172a] via-[#1d4ed8] to-[#ef4444]",
    badge: "Player Pick",
    image: "/kits/processed/may30/kit-45-front.png",
    color: "Dark navy/red",
    stock: 40,
    sizeStock: {
      S: 10,
      M: 10,
      L: 10,
      XL: 10
    },
    backImage: "/kits/processed/may30/kit-45-back.png"
  },
  {
    id: 46,
    name: "Kylian Mbappe",
    club: "Paris Saint-Germain",
    season: "Home 2020-21 - short sleeve",
    price: 1399,
    number: "#7",
    league: "Ligue 1",
    gradient: "from-[#f8fafc] via-[#1d4ed8] to-[#111827]",
    badge: "Player Pick",
    image: "/kits/processed/may30/kit-46-front.png",
    color: "Navy with red/white stripe",
    stock: 40,
    sizeStock: {
      S: 10,
      M: 10,
      L: 10,
      XL: 10
    },
    backImage: "/kits/processed/may30/kit-46-back.png"
  },
  {
    id: 47,
    name: "Kylian Mbappe",
    club: "Paris Saint-Germain",
    season: "Home 2021-22 - short sleeve",
    price: 1399,
    number: "#7",
    league: "Ligue 1",
    gradient: "from-[#0f172a] via-[#1d4ed8] to-[#ef4444]",
    badge: "Player Pick",
    image: "/kits/processed/may30/kit-47-front.png",
    color: "Dark blue/red center stripe",
    stock: 40,
    sizeStock: {
      S: 10,
      M: 10,
      L: 10,
      XL: 10
    },
    backImage: "/kits/processed/may30/kit-47-back.png"
  },
  {
    id: 48,
    name: "Kylian Mbappe",
    club: "France national football team",
    season: "Home 2022 - short sleeve",
    price: 1399,
    number: "#10",
    league: "International",
    gradient: "from-[#facc15] via-[#166534] to-[#ffffff]",
    badge: "Player Pick",
    image: "/kits/processed/may30/kit-48-front.png",
    color: "Navy gold accents",
    stock: 40,
    sizeStock: {
      S: 10,
      M: 10,
      L: 10,
      XL: 10
    },
    backImage: "/kits/processed/may30/kit-48-back.png"
  },
  {
    id: 49,
    name: "Kylian Mbappe",
    club: "Real Madrid CF",
    season: "Home 2024-25 - short sleeve",
    price: 1399,
    number: "#9",
    league: "La Liga",
    gradient: "from-[#facc15] via-[#166534] to-[#ffffff]",
    badge: "Player Pick",
    image: "/kits/processed/may30/kit-49-front.png",
    color: "White/gold trim",
    stock: 40,
    sizeStock: {
      S: 10,
      M: 10,
      L: 10,
      XL: 10
    },
    backImage: "/kits/processed/may30/kit-49-back.png"
  },
  {
    id: 50,
    name: "Kylian Mbappe",
    club: "Real Madrid CF",
    season: "Away 2025-26 - short sleeve",
    price: 1399,
    number: "#9",
    league: "La Liga",
    gradient: "from-[#111111] via-[#3f3f46] to-[#d4af37]",
    badge: "Player Pick",
    image: "/kits/processed/may30/kit-50-front.png",
    color: "Dark grey/orange accents",
    stock: 40,
    sizeStock: {
      S: 10,
      M: 10,
      L: 10,
      XL: 10
    },
    backImage: "/kits/processed/may30/kit-50-back.png"
  },
  {
    id: 51,
    name: "Kylian Mbappe",
    club: "Real Madrid CF",
    season: "Third 2024-25 - short sleeve",
    price: 1399,
    number: "#9",
    league: "La Liga",
    gradient: "from-[#111827] via-[#3f3f46] to-[#f8fafc]",
    badge: "Player Pick",
    image: "/kits/processed/may30/kit-53-front.png",
    color: "Dark grey/white accents",
    stock: 40,
    sizeStock: {
      S: 10,
      M: 10,
      L: 10,
      XL: 10
    },
    backImage: "/kits/processed/may30/kit-53-back.png",
    description: "Real Madrid 2024-25 away-style Mbappe jersey in dark grey with white detailing, a tonal all-over pattern, polo collar, and Mbappe #9 on the back."
  },
  {
    id: 52,
    name: "Kylian Mbappe",
    club: "Real Madrid CF",
    season: "Away 2024-25 - short sleeve",
    price: 1399,
    number: "#9",
    league: "La Liga",
    gradient: "from-[#f97316] via-[#fb923c] to-[#111827]",
    badge: "Player Pick",
    image: "/kits/processed/may30/kit-51-front.png",
    color: "Orange/navy accents",
    stock: 40,
    sizeStock: {
      S: 10,
      M: 10,
      L: 10,
      XL: 10
    },
    backImage: "/kits/processed/may30/kit-51-back.png",
    description: "Real Madrid 2024-25 orange Mbappe jersey with navy shoulder stripes, dark sponsor detailing, Champions League sleeve patches, and Mbappe #9 on the back."
  },
  {
    id: 53,
    name: "Kylian Mbappe",
    club: "Real Madrid CF",
    season: "Third 2025-26 - short sleeve",
    price: 1399,
    number: "#10",
    league: "La Liga",
    gradient: "from-[#f8fafc] via-[#1d4ed8] to-[#0f172a]",
    badge: "Player Pick",
    image: "/kits/processed/mbappe-real-madrid-blue-front.webp",
    color: "Blue/white third",
    stock: 40,
    sizeStock: {
      S: 10,
      M: 10,
      L: 10,
      XL: 10
    },
    backImage: "/kits/processed/mbappe-real-madrid-blue-back.webp",
    description: "Real Madrid 2025-26 Blue Bird third jersey inspired by the Bernabeu, with serrated white shoulder stripes, Trefoil branding, AEROREADY fabric and Mbappe #10 on the back."
  },
  {
    id: 54,
    name: "Lamine Yamal",
    club: "FC Barcelona",
    season: "Home 2023-24 - short sleeve",
    price: 1399,
    number: "#27",
    league: "La Liga",
    gradient: "from-[#c1121f] via-[#7f1d1d] to-[#facc15]",
    badge: "Player Pick",
    image: "/kits/processed/may30/kit-54-front.png",
    color: "Red/blue stripes",
    stock: 40,
    sizeStock: {
      S: 10,
      M: 10,
      L: 10,
      XL: 10
    },
    backImage: "/kits/processed/may30/kit-54-back.png"
  },
  {
    id: 55,
    name: "Lamine Yamal",
    club: "FC Barcelona",
    season: "Away 2023-24 - short sleeve",
    price: 1399,
    number: "#27",
    league: "La Liga",
    gradient: "from-[#f8fafc] via-[#1d4ed8] to-[#111827]",
    badge: "Player Pick",
    image: "/kits/processed/may30/kit-55-front.png",
    color: "White/red cross design",
    stock: 40,
    sizeStock: {
      S: 10,
      M: 10,
      L: 10,
      XL: 10
    },
    backImage: "/kits/processed/may30/kit-55-back.png"
  },
  {
    id: 56,
    name: "Lamine Yamal",
    club: "FC Barcelona",
    season: "Third 2023-24 - short sleeve",
    price: 1399,
    number: "#27",
    league: "La Liga",
    gradient: "from-[#5eead4] via-[#0891b2] to-[#111827]",
    badge: "Player Pick",
    image: "/kits/processed/may30/kit-56-front.png",
    color: "Aqua mint",
    stock: 40,
    sizeStock: {
      S: 10,
      M: 10,
      L: 10,
      XL: 10
    },
    backImage: "/kits/processed/may30/kit-56-back.png"
  },
  {
    id: 57,
    name: "Lamine Yamal",
    club: "FC Barcelona",
    season: "Home 2024-25 - short sleeve",
    price: 1399,
    number: "#19",
    league: "La Liga",
    gradient: "from-[#0f172a] via-[#1d4ed8] to-[#ef4444]",
    badge: "Player Pick",
    image: "/kits/processed/may30/kit-57-front.png",
    color: "Dark navy/red split",
    stock: 40,
    sizeStock: {
      S: 10,
      M: 10,
      L: 10,
      XL: 10
    },
    backImage: "/kits/processed/may30/kit-57-back.png"
  },
  {
    id: 58,
    name: "Lamine Yamal",
    club: "FC Barcelona",
    season: "Away 2024-25 - short sleeve",
    price: 1399,
    number: "#19",
    league: "La Liga",
    gradient: "from-[#111111] via-[#3f3f46] to-[#d4af37]",
    badge: "Player Pick",
    image: "/kits/processed/may30/kit-58-front.png",
    color: "Black/neon green accents",
    stock: 40,
    sizeStock: {
      S: 10,
      M: 10,
      L: 10,
      XL: 10
    },
    backImage: "/kits/processed/may30/kit-58-back.png"
  },
  {
    id: 59,
    name: "Lamine Yamal",
    club: "Spain national football team",
    season: "Home 2024 - short sleeve",
    price: 1399,
    number: "#19",
    league: "International",
    gradient: "from-[#c1121f] via-[#7f1d1d] to-[#facc15]",
    badge: "Player Pick",
    image: "/kits/processed/may30/kit-59-front.png",
    color: "Red/yellow accents",
    stock: 40,
    sizeStock: {
      S: 10,
      M: 10,
      L: 10,
      XL: 10
    },
    backImage: "/kits/processed/may30/kit-59-back.png"
  },
  {
    id: 60,
    name: "Lamine Yamal",
    club: "Spain national football team",
    season: "Away 2024 - short sleeve",
    price: 1399,
    number: "#19",
    league: "International",
    gradient: "from-[#facc15] via-[#166534] to-[#ffffff]",
    badge: "Player Pick",
    image: "/kits/processed/may30/kit-60-front.png",
    color: "Light yellow/pastel blue",
    stock: 40,
    sizeStock: {
      S: 10,
      M: 10,
      L: 10,
      XL: 10
    },
    backImage: "/kits/processed/may30/kit-60-back.png"
  },
  {
    id: 61,
    name: "Virgil van Dijk",
    club: "Netherlands",
    season: "Home 2026 - short sleeve",
    price: 1399,
    number: "#4",
    league: "International",
    gradient: "from-[#f97316] via-[#fb923c] to-[#111827]",
    badge: "2026 WC",
    image: "/kits/processed/july5-drop/netherlands-home-2026-virgil-front.png",
    color: "Orange/black home",
    stock: 40,
    sizeStock: {
      S: 10,
      M: 10,
      L: 10,
      XL: 10
    },
    backImage: "/kits/processed/july5-drop/netherlands-home-2026-virgil-back.png",
    description: "Netherlands Home 2026 Virgil van Dijk jersey in bright orange with black trim, World Cup sleeve patch styling, and Virgil #4 on the back."
  },
  {
    id: 62,
    name: "Virgil van Dijk",
    club: "Netherlands",
    season: "Away 2026 - short sleeve",
    price: 1399,
    number: "#4",
    league: "International",
    gradient: "from-[#f8fafc] via-[#fb923c] to-[#111827]",
    badge: "2026 WC",
    image: "/kits/processed/july5-drop/netherlands-away-2026-virgil-front.png",
    color: "White/orange away",
    stock: 40,
    sizeStock: {
      S: 10,
      M: 10,
      L: 10,
      XL: 10
    },
    backImage: "/kits/processed/july5-drop/netherlands-away-2026-virgil-back.png",
    description: "Netherlands Away 2026 Virgil van Dijk jersey in white with orange detailing, a bold chest band, and Virgil #4 on the back."
  },
  {
    id: 63,
    name: "Nicolo Barella",
    club: "Italy",
    season: "Away 2026 - short sleeve",
    price: 1399,
    number: "#18",
    league: "International",
    gradient: "from-[#f8fafc] via-[#cbd5e1] to-[#1e3a8a]",
    badge: "2026 WC",
    image: "/kits/processed/july5-drop/italy-away-2026-barella-front.png",
    color: "White/navy/gold away",
    stock: 40,
    sizeStock: {
      S: 10,
      M: 10,
      L: 10,
      XL: 10
    },
    backImage: "/kits/processed/july5-drop/italy-away-2026-barella-back.png",
    description: "Italy Away 2026 Barella jersey in white with navy and gold trim, Italia crest styling, and Barella #18 on the back."
  },
  {
    id: 64,
    name: "Nicolo Barella",
    club: "Italy",
    season: "Home 2026 - short sleeve",
    price: 1399,
    number: "#18",
    league: "International",
    gradient: "from-[#1d4ed8] via-[#1e3a8a] to-[#d4af37]",
    badge: "2026 WC",
    image: "/kits/processed/july5-drop/italy-home-2026-barella-front.png",
    color: "Blue/gold home",
    stock: 40,
    sizeStock: {
      S: 10,
      M: 10,
      L: 10,
      XL: 10
    },
    backImage: "/kits/processed/july5-drop/italy-home-2026-barella-back.png",
    description: "Italy Home 2026 Barella jersey in royal blue with gold detailing, tonal pattern, and Barella #18 on the back."
  },
  {
    id: 65,
    name: "Kaoru Mitoma",
    club: "Japan",
    season: "Home 2026 - short sleeve",
    price: 1399,
    number: "#7",
    league: "International",
    gradient: "from-[#1d4ed8] via-[#0f172a] to-[#f8fafc]",
    badge: "2026 WC",
    image: "/kits/processed/july5-drop/japan-home-2026-mitoma-front.png",
    color: "Blue/white home",
    stock: 40,
    sizeStock: {
      S: 10,
      M: 10,
      L: 10,
      XL: 10
    },
    backImage: "/kits/processed/july5-drop/japan-home-2026-mitoma-back.png",
    description: "Japan Home 2026 Mitoma jersey in deep blue with white shoulder stripes, Japan crest, and Mitoma #7 on the back."
  },
  {
    id: 68,
    name: "McLaren Team T-shirt",
    club: "McLaren",
    season: "Team T-shirt 2025",
    price: 1299,
    number: "F1",
    league: "Formula 1",
    gradient: "from-[#ff7a00] via-[#111111] to-[#ffffff]",
    badge: "F1",
    image: "/kits/f1/mclaren-team-2025-front.png",
    color: "Papaya orange teamwear",
    productType: "f1",
    customizationAvailable: false,
    stock: 40,
    sizeStock: { S: 10, M: 10, L: 10, XL: 10 },
    backImage: "/kits/f1/mclaren-team-2025-back.png",
    description: "McLaren 2025 team T-shirt with papaya racing colors and clean motorsport styling."
  },
  {
    id: 69,
    name: "RB Off White Track Polo",
    club: "Racing Bulls",
    season: "Off White Track Polo",
    price: 1299,
    number: "F1",
    league: "Formula 1",
    gradient: "from-[#f8fafc] via-[#0f172a] to-[#ef4444]",
    badge: "F1",
    image: "/kits/f1/rb-off-white-track-polo-front.png",
    color: "Off white/navy/red polo",
    productType: "f1",
    customizationAvailable: true,
    stock: 40,
    sizeStock: { S: 10, M: 10, L: 10, XL: 10 },
    backImage: "/kits/f1/rb-off-white-track-polo-back.png",
    description: "RB off white track polo with racing sponsor details, clean teamwear finish, and optional customisation."
  },
  {
    id: 70,
    name: "SF White Oversized T-shirt",
    club: "Ferrari",
    season: "White Oversized T-shirt",
    price: 1299,
    number: "F1",
    league: "Formula 1",
    gradient: "from-[#ffffff] via-[#d4af37] to-[#dc2626]",
    badge: "F1",
    image: "/kits/f1/sf-white-oversized-front.png",
    color: "White Ferrari oversized",
    productType: "f1",
    customizationAvailable: true,
    stock: 40,
    sizeStock: { S: 10, M: 10, L: 10, XL: 10 },
    backImage: "/kits/f1/sf-white-oversized-back.png",
    description: "Ferrari white oversized T-shirt with front and back racing graphics and optional customisation."
  },
  {
    id: 71,
    name: "SF Racing Rosso Oversized T-shirt",
    club: "Ferrari",
    season: "Racing Rosso T-shirt 2025",
    price: 1299,
    number: "F1",
    league: "Formula 1",
    gradient: "from-[#dc2626] via-[#7f1d1d] to-[#facc15]",
    badge: "F1",
    image: "/kits/f1/sf-racing-rosso-oversized-2025-front.png",
    color: "Ferrari rosso oversized",
    productType: "f1",
    customizationAvailable: true,
    stock: 40,
    sizeStock: { S: 10, M: 10, L: 10, XL: 10 },
    backImage: "/kits/f1/sf-racing-rosso-oversized-2025-back.png",
    description: "Ferrari racing rosso oversized T-shirt with team-style front and back graphics and optional customisation."
  },
  {
    id: 72,
    name: "Mercedes White Oversized Team T-shirt",
    club: "Mercedes-AMG",
    season: "White Oversized Team T-shirt",
    price: 1299,
    number: "F1",
    league: "Formula 1",
    gradient: "from-[#ffffff] via-[#d1d5db] to-[#00a19c]",
    badge: "F1",
    image: "/kits/f1/mercedes-white-oversized-front.png",
    color: "White Mercedes oversized",
    productType: "f1",
    customizationAvailable: true,
    stock: 40,
    sizeStock: { S: 10, M: 10, L: 10, XL: 10 },
    backImage: "/kits/f1/mercedes-white-oversized-back.png",
    description: "Mercedes white oversized team T-shirt with Petronas-style racing details and optional customisation."
  },
  {
    id: 73,
    name: "RB World Champion Polo",
    club: "Red Bull Racing",
    season: "World Champion Polo",
    price: 1299,
    number: "F1",
    league: "Formula 1",
    gradient: "from-[#0f172a] via-[#1d4ed8] to-[#ef4444]",
    badge: "F1",
    image: "/kits/f1/rb-world-champion-polo-front.png",
    color: "Navy Red Bull polo",
    productType: "f1",
    customizationAvailable: false,
    stock: 40,
    sizeStock: { S: 10, M: 10, L: 10, XL: 10 },
    backImage: "/kits/f1/rb-world-champion-polo-back.png",
    description: "Red Bull Racing world champion polo with front and back team sponsor details."
  },
  {
    id: 74,
    name: "SF Racing 2026 Performance Team T-shirt",
    club: "Ferrari",
    season: "Performance Team T-shirt 2026",
    price: 1299,
    number: "F1",
    league: "Formula 1",
    gradient: "from-[#dc2626] via-[#991b1b] to-[#ffffff]",
    badge: "F1",
    image: "/kits/f1/sf-racing-2026-performance-front.png",
    color: "Ferrari red performance",
    productType: "f1",
    customizationAvailable: false,
    stock: 40,
    sizeStock: { S: 10, M: 10, L: 10, XL: 10 },
    backImage: "/kits/f1/sf-racing-2026-performance-back.png",
    description: "Ferrari 2026 performance team T-shirt with race-day sponsor styling."
  },
  {
    id: 75,
    name: "Mercedes White Team T-shirt",
    club: "Mercedes-AMG",
    season: "White Team T-shirt 2025",
    price: 1299,
    number: "F1",
    league: "Formula 1",
    gradient: "from-[#ffffff] via-[#d1d5db] to-[#111111]",
    badge: "F1",
    image: "/kits/f1/mercedes-white-team-2025-front.png",
    color: "White Mercedes teamwear",
    productType: "f1",
    customizationAvailable: false,
    stock: 40,
    sizeStock: { S: 10, M: 10, L: 10, XL: 10 },
    backImage: "/kits/f1/mercedes-white-team-2025-back.png",
    description: "Mercedes white team T-shirt 2025 with clean motorsport sponsor details."
  },
  {
    id: 76,
    name: "Mercedes Black Oversized Team T-shirt",
    club: "Mercedes-AMG",
    season: "Black Oversized Team T-shirt",
    price: 1299,
    number: "F1",
    league: "Formula 1",
    gradient: "from-[#111111] via-[#27272a] to-[#00a19c]",
    badge: "F1",
    image: "/kits/f1/mercedes-black-oversized-front.png",
    color: "Black Mercedes oversized",
    productType: "f1",
    customizationAvailable: true,
    stock: 40,
    sizeStock: { S: 10, M: 10, L: 10, XL: 10 },
    backImage: "/kits/f1/mercedes-black-oversized-back.png",
    description: "Mercedes black oversized team T-shirt with back sponsor details and optional customisation."
  },
  {
    id: 77,
    name: "RB 2026 Polo Team T-shirt",
    club: "Red Bull Racing",
    season: "Polo Team T-shirt 2026",
    price: 1299,
    number: "F1",
    league: "Formula 1",
    gradient: "from-[#1d4ed8] via-[#0f172a] to-[#ef4444]",
    badge: "F1",
    image: "/kits/f1/rb-2026-polo-team-front.png",
    color: "Blue/navy Red Bull polo",
    productType: "f1",
    customizationAvailable: true,
    stock: 40,
    sizeStock: { S: 10, M: 10, L: 10, XL: 10 },
    backImage: "/kits/f1/rb-2026-polo-team-back.png",
    description: "Red Bull Racing 2026 polo team T-shirt with race sponsor styling and optional customisation."
  },
  {
    id: 78,
    name: "Mercedes Black Team T-shirt",
    club: "Mercedes-AMG",
    season: "Black Team T-shirt 2025",
    price: 1299,
    number: "F1",
    league: "Formula 1",
    gradient: "from-[#111111] via-[#27272a] to-[#00a19c]",
    badge: "F1",
    image: "/kits/f1/mercedes-black-team-2025-front.png",
    color: "Black Mercedes teamwear",
    productType: "f1",
    customizationAvailable: true,
    stock: 40,
    sizeStock: { S: 10, M: 10, L: 10, XL: 10 },
    backImage: "/kits/f1/mercedes-black-team-2025-back.png",
    description: "Mercedes black team T-shirt 2025 with clean sponsor details and optional customisation."
  },
  {
    id: 66,
    name: "Mystery Kit",
    club: "World Cup Surprise",
    season: "2026 Mystery Box - short sleeve",
    price: 1299,
    number: "#?",
    league: "International",
    gradient: "from-[#111111] via-[#d4af37] to-[#f8fafc]",
    badge: "Mystery",
    image: "/kits/processed/july5-drop/mystery-kit-2026.png",
    color: "Mystery world cup jersey",
    stock: 40,
    sizeStock: {
      S: 10,
      M: 10,
      L: 10,
      XL: 10
    },
    backImage: "/kits/processed/july5-drop/mystery-kit-2026.png",
    description: "A surprise World Cup jersey picked from global teams. You choose the size, and you have a chance to receive a Fan, Player, or Master version."
  },
  ...textOnlyJackets,
  ...textOnlyRetroPlayerKits,
  ...newClubDropKits,
];

const IMPORTED_FROM_THAILAND_NOTE = "Imported from Thailand."

const VERIFIED_CATALOG_IMAGES: Record<number, { image: string; backImage: string }> = {
  2: { image: "/kits/remade/portugal-2026-away-ronaldo-front.jpg", backImage: "/kits/remade/portugal-2026-away-ronaldo-back.jpg" },
  6: { image: "/kits/remade/france-2026-home-mbappe-front.jpg", backImage: "/kits/remade/france-2026-home-mbappe-back.jpg" },
  7: { image: "/kits/remade/france-2026-away-mbappe-front.jpg", backImage: "/kits/remade/france-2026-away-mbappe-back.jpg" },
  4: { image: "/kits/processed/standardized-source/source-15-single.webp", backImage: "/kits/processed/spain-2026-home-back.webp" },
  11: { image: "/kits/processed/standardized-source/source-16-single.webp", backImage: "/kits/processed/standardized-source/source-17-single.webp" },
  12: { image: "/kits/processed/standardized-source/source-18-single.webp", backImage: "/kits/processed/standardized-source/source-19-single.webp" },
  13: { image: "/kits/processed/standardized-source/source-20-single.webp", backImage: "/kits/processed/standardized-source/source-21-single.webp" },
  14: { image: "/kits/processed/standardized-source/source-22-single.webp", backImage: "/kits/processed/standardized-source/source-23-single.webp" },
  15: { image: "/kits/processed/standardized-source/source-25-single.webp", backImage: "/kits/processed/standardized-source/source-24-single.webp" },
  17: { image: "/kits/processed/standardized-source/source-28-front.webp", backImage: "/kits/processed/standardized-source/source-28-back.webp" },
  18: { image: "/kits/processed/standardized-source/source-29-front.webp", backImage: "/kits/processed/standardized-source/source-29-back.webp" },
  19: { image: "/kits/processed/standardized-source/source-30-front.webp", backImage: "/kits/processed/standardized-source/source-30-back.webp" },
  20: { image: "/kits/processed/standardized-source/source-31-front.webp", backImage: "/kits/processed/standardized-source/source-31-back.webp" },
  21: { image: "/kits/processed/standardized-source/source-32-front.webp", backImage: "/kits/processed/standardized-source/source-32-back.webp" },
  22: { image: "/kits/processed/standardized-source/source-71-front.webp", backImage: "/kits/processed/standardized-source/source-71-back.webp" },
  23: { image: "/kits/processed/standardized-source/source-34-front.webp", backImage: "/kits/processed/standardized-source/source-34-back.webp" },
  24: { image: "/kits/processed/standardized-source/source-35-front.webp", backImage: "/kits/processed/standardized-source/source-35-back.webp" },
  25: { image: "/kits/processed/standardized-source/source-36-front.webp", backImage: "/kits/processed/standardized-source/source-36-back.webp" },
  26: { image: "/kits/processed/standardized-source/source-37-front.webp", backImage: "/kits/processed/standardized-source/source-37-back.webp" },
  27: { image: "/kits/processed/standardized-source/source-39-front.webp", backImage: "/kits/processed/standardized-source/source-39-back.webp" },
  28: { image: "/kits/processed/standardized-source/source-40-front.webp", backImage: "/kits/processed/standardized-source/source-40-back.webp" },
  29: { image: "/kits/processed/standardized-source/source-33-front.webp", backImage: "/kits/processed/standardized-source/source-33-back.webp" },
  30: { image: "/kits/processed/standardized-source/source-41-front.webp", backImage: "/kits/processed/standardized-source/source-41-back.webp" },
  31: { image: "/kits/processed/standardized-source/source-42-front.webp", backImage: "/kits/processed/standardized-source/source-42-back.webp" },
  33: { image: "/kits/processed/standardized-source/source-44-front.webp", backImage: "/kits/processed/standardized-source/source-44-back.webp" },
  34: { image: "/kits/processed/standardized-source/source-45-front.webp", backImage: "/kits/processed/standardized-source/source-45-back.webp" },
  35: { image: "/kits/processed/standardized-source/source-43-front.webp", backImage: "/kits/processed/standardized-source/source-43-back.webp" },
  36: { image: "/kits/processed/standardized-source/source-46-front.webp", backImage: "/kits/processed/standardized-source/source-46-back.webp" },
  37: { image: "/kits/processed/standardized-source/source-47-front.webp", backImage: "/kits/processed/standardized-source/source-47-back.webp" },
  38: { image: "/kits/processed/standardized-source/source-48-front.webp", backImage: "/kits/processed/standardized-source/source-48-back.webp" },
  39: { image: "/kits/processed/standardized-source/source-49-front.webp", backImage: "/kits/processed/standardized-source/source-49-back.webp" },
  40: { image: "/kits/processed/standardized-source/source-50-front.webp", backImage: "/kits/processed/standardized-source/source-50-back.webp" },
  41: { image: "/kits/processed/standardized-source/source-51-front.webp", backImage: "/kits/processed/standardized-source/source-51-back.webp" },
  42: { image: "/kits/processed/standardized-source/source-52-front.webp", backImage: "/kits/processed/standardized-source/source-52-back.webp" },
  43: { image: "/kits/processed/standardized-source/source-53-front.webp", backImage: "/kits/processed/standardized-source/source-53-back.webp" },
  44: { image: "/kits/processed/standardized-source/source-54-front.webp", backImage: "/kits/processed/standardized-source/source-54-back.webp" },
  45: { image: "/kits/processed/standardized-source/source-55-front.webp", backImage: "/kits/processed/standardized-source/source-55-back.webp" },
  46: { image: "/kits/processed/standardized-source/source-56-front.webp", backImage: "/kits/processed/standardized-source/source-56-back.webp" },
  47: { image: "/kits/processed/standardized-source/source-57-front.webp", backImage: "/kits/processed/standardized-source/source-57-back.webp" },
  48: { image: "/kits/processed/standardized-source/source-58-front.webp", backImage: "/kits/processed/standardized-source/source-58-back.webp" },
  49: { image: "/kits/processed/standardized-source/source-59-front.webp", backImage: "/kits/processed/standardized-source/source-59-back.webp" },
  50: { image: "/kits/processed/standardized-source/source-60-front.webp", backImage: "/kits/processed/standardized-source/source-60-back.webp" },
  51: { image: "/kits/processed/standardized-source/source-61-front.webp", backImage: "/kits/processed/standardized-source/source-61-back.webp" },
  52: { image: "/kits/processed/standardized-source/source-62-front.webp", backImage: "/kits/processed/standardized-source/source-62-back.webp" },
  53: { image: "/kits/processed/mbappe-real-madrid-blue-front.webp", backImage: "/kits/processed/mbappe-real-madrid-blue-back.webp" },
  54: { image: "/kits/processed/standardized-source/source-64-front.webp", backImage: "/kits/processed/standardized-source/source-64-back.webp" },
  55: { image: "/kits/processed/standardized-source/source-65-front.webp", backImage: "/kits/processed/standardized-source/source-65-back.webp" },
  56: { image: "/kits/processed/standardized-source/source-66-front.webp", backImage: "/kits/processed/standardized-source/source-66-back.webp" },
  57: { image: "/kits/processed/standardized-source/source-67-front.webp", backImage: "/kits/processed/standardized-source/source-67-back.webp" },
  58: { image: "/kits/processed/standardized-source/source-68-front.webp", backImage: "/kits/processed/standardized-source/source-68-back.webp" },
  59: { image: "/kits/processed/standardized-source/source-69-front.webp", backImage: "/kits/processed/standardized-source/source-69-back.webp" },
  60: { image: "/kits/processed/standardized-source/source-70-front.webp", backImage: "/kits/processed/standardized-source/source-70-back.webp" },
  61: { image: "/kits/processed/standardized-source/source-01-front.webp", backImage: "/kits/processed/standardized-source/source-01-back.webp" },
  62: { image: "/kits/processed/standardized-source/source-02-front.webp", backImage: "/kits/processed/standardized-source/source-02-back.webp" },
  63: { image: "/kits/processed/standardized-source/source-04-front.webp", backImage: "/kits/processed/standardized-source/source-04-back.webp" },
  64: { image: "/kits/processed/standardized-source/source-03-front.webp", backImage: "/kits/processed/standardized-source/source-03-back.webp" },
  65: { image: "/kits/processed/standardized-source/source-05-front.webp", backImage: "/kits/processed/standardized-source/source-05-back.webp" },
}

function withCatalogVariants(items: Kit[]): Kit[] {
  return items.map((kit) => ({
    ...kit,
    ...(VERIFIED_CATALOG_IMAGES[kit.id] || {}),
    // A verified jersey photo makes the product safe to publish even if its old record was a draft.
    ...(VERIFIED_CATALOG_IMAGES[kit.id] ? { isDraft: false } : {}),
    productType: kit.productType || "jersey" as const,
    description: kit.productType === "f1"
      ? kit.description || buildDefaultJerseyDescription(kit)
      : appendImportedNote(kit.description || buildDefaultJerseyDescription(kit)),
  }))
}

function appendImportedNote(description: string) {
  return description.includes(IMPORTED_FROM_THAILAND_NOTE)
    ? description
    : `${description} ${IMPORTED_FROM_THAILAND_NOTE}`
}

function buildDefaultJerseyDescription(kit: Kit) {
  return `${kit.club} ${kit.season} jersey for ${kit.name}, featuring ${String(kit.color || "classic").toLowerCase()} styling and ${kit.number} on the back.`
}

export const kits: Kit[] = withCatalogVariants([...baseKits, ...suppliedArchiveKits])


